import ProjectDescription
import ProjectDescriptionHelpers

let modules: [Target] =
    // Depends on ZstdKit for Tape.archived()/Tape(archivedData:)'s binary tape export format.
    Module.framework(name: "SortEngineKit", dependencies: [.target(name: "ZstdKit")]) +
    // Decode-only, pure-Swift Zstandard implementation — no dependencies beyond Foundation, no
    // C/C++ interop. See COMPRESSION_DESIGN.md for why. Test fixtures are
    // binary `.zst`/`.expected` pairs generated by Modules/ZstdKit/FixtureGenerator/, so they need
    // an explicit testResources glob to be bundled into ZstdKitTests.
    Module.framework(
        name: "ZstdKit",
        testResources: [.glob(pattern: "Modules/ZstdKit/Tests/Fixtures/**")]
    ) +
    Module.framework(name: "AlgorithmKit", dependencies: [.target(name: "SortEngineKit")]) +
    Module.framework(name: "VisualizationKit", dependencies: [.target(name: "SortEngineKit")]) +
    Module.framework(name: "BuiltInAlgorithms", dependencies: [.target(name: "AlgorithmKit")]) +
    Module.framework(name: "BuiltInVisualizers", dependencies: [.target(name: "VisualizationKit")]) +
    Module.framework(name: "SettingsKit", dependencies: [.target(name: "VisualizationKit"), .target(name: "AlgorithmKit")]) +
    // ToneKit reimplements just the AudioKit/AudioKitEX/SoundpipeAudioKit subset AudioService
    // actually needs directly on AVAudioEngine — see Modules/ToneKit/NOTICE.md — so AudioEngineKit
    // no longer needs any external audio package at all.
    Module.framework(name: "ToneKit") +
    Module.framework(name: "AudioEngineKit", dependencies: [
        .target(name: "ToneKit"), .target(name: "SettingsKit"),
    ]) +
    Module.framework(name: "PersistenceKit", dependencies: [
        .target(name: "SortEngineKit"), .target(name: "AlgorithmKit"),
    ]) +
    Module.framework(name: "DesignSystemKit", dependencies: [
        .target(name: "SettingsKit"),
    ]) +
    Module.framework(name: "MathRenderingKit", dependencies: [
        .external(name: "SwiftMath"), .target(name: "AlgorithmKit"),
    ]) +
    // `AlgorithmDetailStore` decodes `AlgorithmDetails.algz` via ZstdKit; its equivalence tests
    // need the real archive bundled into SortFeatureTests too (mirroring ZstdKit's own
    // `testResources` glob for its binary fixtures), and need `import ZstdKit` directly (module
    // visibility isn't transitive), hence `testDependencies`.
    Module.framework(
        name: "SortFeature",
        dependencies: [
            .target(name: "SortEngineKit"), .target(name: "AlgorithmKit"), .target(name: "VisualizationKit"),
            .target(name: "AudioEngineKit"), .target(name: "SettingsKit"), .target(name: "DesignSystemKit"),
            .target(name: "PersistenceKit"), .target(name: "MathRenderingKit"), .target(name: "ZstdKit"),
            .external(name: "MarkdownUI"),
        ],
        testResources: [.glob(pattern: "App/Resources/AlgorithmDetails/AlgorithmDetails.algz")],
        testDependencies: [.target(name: "ZstdKit")]
    ) +
    Module.framework(name: "SettingsFeature", dependencies: [
        .target(name: "SettingsKit"), .target(name: "VisualizationKit"), .target(name: "AlgorithmKit"),
        .target(name: "AudioEngineKit"), .target(name: "DesignSystemKit"),
    ]) +
    Module.framework(name: "HomeFeature", dependencies: [
        .target(name: "DesignSystemKit"), .external(name: "MarkdownUI"),
    ]) +
    // App Intents surface: entities/queries wrapping AlgorithmRegistry/VisualizerRegistry/
    // ShuffleRegistry/AutomationRegistry, a SortCoordinator bridging intents into the live
    // SwiftUI selection/session state, and the intents/AppShortcutsProvider themselves.
    Module.framework(name: "IntentsKit", dependencies: [
        .target(name: "AlgorithmKit"), .target(name: "VisualizationKit"),
        .target(name: "SortFeature"), .target(name: "SettingsKit"),
    ])

let app = Target.target(
    // Not "Sort Symphony" (with the space `productName` below deliberately avoids): Xcode's
    // build system names each target's own "-deps.modulemap" file after the *target* name, not
    // `productName`/the module name, so a space here leaks into a real file path
    // (`Derived/ModuleMaps/Sort Symphony-deps.modulemap`) that `swiftc` tolerates but `actool`'s
    // asset-symbol-generation dependency scanner does not -- it truncates at the space and fails
    // with "module map file '.../ModuleMaps/Sort' not found" (hit this for real once Xcode Cloud
    // picked up an `actool` version where that scanning path started running). The app's visible
    // name stays "Sort Symphony" via the explicit `CFBundleDisplayName` override below.
    name: "SortSymphony",
    destinations: Module.destinations,
    product: .app,
    productName: "SortSymphony",
    bundleId: "com.nhubbard.Sort2.mobile",
    deploymentTargets: Module.deploymentTargets,
    infoPlist: .extendingDefault(with: [
        // All 4 orientations, no UIRequiresFullScreen: Apple has announced that flag will stop
        // being honored in a future iPadOS release, so "declare landscape-only + opt out of
        // multitasking" is no longer a viable way to stay full-screen-and-wide — the OS will let
        // the app rotate/resize into Split View and Slide Over regardless of what's declared here.
        // RunControlBar/AlgorithmDetailSection respond to the narrower widths this permits
        // (portrait and multitasking both just mean "less width," handled the same way).
        "UISupportedInterfaceOrientations": [
            "UIInterfaceOrientationLandscapeLeft", "UIInterfaceOrientationLandscapeRight",
            "UIInterfaceOrientationPortrait", "UIInterfaceOrientationPortraitUpsideDown",
        ],
        "UISupportedInterfaceOrientations~ipad": [
            "UIInterfaceOrientationLandscapeLeft", "UIInterfaceOrientationLandscapeRight",
            "UIInterfaceOrientationPortrait", "UIInterfaceOrientationPortraitUpsideDown",
        ],
        "LSApplicationCategoryType": "public.app-category.education",
        "UIApplicationSupportsIndirectInputEvents": true,
        "ITSAppUsesNonExemptEncryption": false,
        // Empty dict opts into the system-generated default launch screen (app icon centered on
        // background color) — no storyboard needed. Newly enforced by App Store validation as of
        // the iOS 26/27 SDK; wasn't required in earlier submissions.
        "UILaunchScreen": [:],
        "UIApplicationSceneManifest": [
            "UIApplicationSupportsMultipleScenes": false,
        ],
        "CFBundleShortVersionString": "$(MARKETING_VERSION)",
        "CFBundleVersion": "$(CURRENT_PROJECT_VERSION)",
        // Explicit, rather than relying on whatever Tuist/Xcode falls back to by default --
        // `name`/`productName` above are both space-free ("SortSymphony") for the module-map
        // reason explained on `app`'s own `name:`, so nothing else here guarantees the user-facing
        // app name still reads as "Sort Symphony".
        "CFBundleDisplayName": "Sort Symphony",
        // Backs `UTType.tapeArchive` (`TapeArchiveDocument.swift`) — a `.tape`-extension file
        // ShareLink can export a recorded/imported tape to, and `.fileImporter` can filter to.
        "UTExportedTypeDeclarations": [
            [
                "UTTypeIdentifier": "com.nhubbard.Sort2.mobile.tapearchive",
                "UTTypeDescription": "Sort Symphony Tape",
                "UTTypeConformsTo": ["public.data"],
                "UTTypeTagSpecification": [
                    "public.filename-extension": ["tape"]
                ],
            ]
        ],
    ]),
    sources: ["App/Sources/**"],
    resources: [
        .glob(pattern: "App/Resources/**", excluding: [
            "App/Resources/AlgorithmDetails/**",
            // Already referenced directly via `entitlements:`/`CODE_SIGN_ENTITLEMENTS` below — left
            // in this glob too, Tuist warns it's being copied into the product as a plain resource.
            "App/Resources/SortSymphony.entitlements",
            // Icon Composer's `.icon` bundle isn't a resource type Tuist's generator recognizes
            // yet (unlike `.imageset`/`.colorset`/`.xcassets` itself) — globbing its individual
            // files (icon.json, Assets/*.svg), whether loose or nested inside Assets.xcassets,
            // fails generation ("trying to add a file... to a build phase that hasn't been added
            // to the project"). Kept as a sibling of Assets.xcassets (not nested inside it) and
            // referenced as its own `.folderReference` below instead.
            "App/Resources/AppIcon.icon/**",
        ]),
        // Real folder reference, not a glob — see the exclusion comment above for why.
        .folderReference(path: "App/Resources/AppIcon.icon"),
        // AlgorithmDetails/ also holds the authoring pipeline (highlight.py, test.py, template/,
        // manage.py, ...) and each algorithm folder's raw/highlighted source, as siblings of the
        // one file actually read at runtime — the exclusion glob above keeps all of that out, so
        // this one explicit carve-out is needed to ship the archive itself.
        // `AlgorithmDetailStore` reads it via `Bundle.main.url(forResource: "AlgorithmDetails",
        // withExtension: "algz")`. `ResourceFileElement` has no `.file(path:)` case — an exact,
        // non-wildcard path is a valid glob pattern instead.
        .glob(pattern: "App/Resources/AlgorithmDetails/AlgorithmDetails.algz"),
    ],
    entitlements: .file(path: "App/Resources/SortSymphony.entitlements"),
    dependencies: [
        .target(name: "SortFeature"), .target(name: "SettingsFeature"),
        .target(name: "HomeFeature"), .target(name: "IntentsKit"),
        .target(name: "MathRenderingKit"),
        // Every AppIntent/AppEntity/AppShortcutsProvider conformance actually lives in IntentsKit,
        // not here — but Xcode's App Intents metadata processor only exports a target's Shortcuts
        // into the *app bundle* when the app target itself directly links AppIntents.framework,
        // not merely transitively through a framework dependency that imports it. Without this,
        // the build logs "Metadata extraction skipped. No AppIntents.framework dependency found"
        // and `SortSymphonyShortcuts` never reaches the Shortcuts app.
        .sdk(name: "AppIntents", type: .framework),
        // Sort2App wires each module's concrete conformances into its registry
        // (AlgorithmRegistry/VisualizerRegistry), which has no visibility into either module
        // itself — both need to be referenced directly by the App target for that.
        .target(name: "BuiltInAlgorithms"), .target(name: "BuiltInVisualizers"),
        // Composition-root registry wiring (AlgorithmKit's AlgorithmRegistry/ShuffleRegistry) needs
        // it directly — it's not re-exported by any of the above. DesignSystemKit is needed
        // directly too, for ContentView's CustomIconLabel sidebar rows (Phase 9) —
        // SortFeature/SettingsFeature/HomeFeature all depend on it already, but don't re-export it.
        .target(name: "AlgorithmKit"), .target(name: "DesignSystemKit"),
        .target(name: "SettingsKit"),
    ],
    settings: .settings(base: [
        "CODE_SIGN_ENTITLEMENTS": "App/Resources/SortSymphony.entitlements",
        "MARKETING_VERSION": "2.0.0",
        "CURRENT_PROJECT_VERSION": "35",
        "SWIFT_VERSION": "6.0",
        "SWIFT_STRICT_CONCURRENCY": "complete",
        "CODE_SIGN_STYLE": "Automatic",
        "DEVELOPMENT_TEAM": "676UP3S3AH",
        // Tuist's default template sets CODE_SIGN_IDENTITY[sdk=macosx*] to "-" (ad-hoc) on every
        // target, which silently overrides DEVELOPMENT_TEAM for Mac Catalyst specifically (it
        // builds against the macosx SDK) and breaks entitlements requiring a real certificate
        // (CloudKit, aps-environment). Override back to a real identity, matching the shipping
        // v1 project's explicit setting. Scoped to macosx only — an unscoped override here would
        // also pin iphoneos builds to "Apple Development", blocking Automatic signing from
        // switching to an Apple Distribution identity for App Store archives.
        "CODE_SIGN_IDENTITY[sdk=macosx*]": "Apple Development",
        "ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS": "YES",
        "ENABLE_USER_SCRIPT_SANDBOXING": "YES",
        "STRING_CATALOG_GENERATE_SYMBOLS": "YES",
    ])
)

let appUITests = Target.target(
    name: "Sort SymphonyUITests",
    destinations: Module.destinations,
    product: .uiTests,
    productName: "SortSymphonyUITests",
    bundleId: "com.nhubbard.Sort2.mobile.uitests",
    deploymentTargets: Module.deploymentTargets,
    sources: ["App/UITests/**"],
    dependencies: [.target(name: "SortSymphony")],
    settings: .settings(base: Module.baseSettings)
)

let project = Project(
    name: "Sort Symphony",
    targets: modules + [app, appUITests]
)