// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "abap" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct AbapTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#ffffff")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#ffffff")!),
      .keyword: TextFormat(fg: Color(fromHex: "#00f")!, bg: Color(fromHex: "#ffffff")!),
      .name: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#ffffff")!),
      .number: TextFormat(fg: Color(fromHex: "#3af")!, bg: Color(fromHex: "#ffffff")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#00f")!, bg: Color(fromHex: "#ffffff")!),
      .string: TextFormat(fg: Color(fromHex: "#5a2")!, bg: Color(fromHex: "#ffffff")!),
    ]
  }
}
