// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "algol" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct AlgolTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#ffffff")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .keyword: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true, underline: true),
      .keywordDeclaration: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true, underline: true),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true),
      .nameClass: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true),
      .nameConstant: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true),
      .nameFunction: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true),
      .nameVariable: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true),
      .operatorWord: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .string: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#ffffff")!, italic: true)
    ]
  }
}
