// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "algol" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct AlgolTheme: CodeTheme {
  public init() {}

  private static let hex000000: UInt32 = 0x000000ff
  private static let hex666: UInt32 = 0x666ff
  private static let hex888: UInt32 = 0x888ff
  private static let hexffffff: UInt32 = 0xffffffff

  public func getBgColor() -> Color { Color(rgba: Self.hexffffff) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hex888), bg: Color(rgba: Self.hexffffff), italic: true),
      .commentPreproc: TextFormat(fg: Color(rgba: Self.hex888), bg: Color(rgba: Self.hexffffff), bold: true),
      .commentSpecial: TextFormat(fg: Color(rgba: Self.hex888), bg: Color(rgba: Self.hexffffff), bold: true),
      .keyword: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true, underline: true),
      .keywordDeclaration: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true, italic: true, underline: true),
      .nameBuiltin: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true, italic: true),
      .nameClass: TextFormat(fg: Color(rgba: Self.hex666), bg: Color(rgba: Self.hexffffff), bold: true, italic: true),
      .nameConstant: TextFormat(fg: Color(rgba: Self.hex666), bg: Color(rgba: Self.hexffffff), bold: true, italic: true),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hex666), bg: Color(rgba: Self.hexffffff), bold: true, italic: true),
      .nameNamespace: TextFormat(fg: Color(rgba: Self.hex666), bg: Color(rgba: Self.hexffffff), bold: true, italic: true),
      .nameVariable: TextFormat(fg: Color(rgba: Self.hex666), bg: Color(rgba: Self.hexffffff), bold: true, italic: true),
      .operatorWord: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true),
      .string: TextFormat(fg: Color(rgba: Self.hex666), bg: Color(rgba: Self.hexffffff), italic: true),
    ]
  }
}
