// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "arduino" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct ArduinoTheme: CodeTheme {
  public init() {}

  private static let hex000000: UInt32 = 0x000000ff
  private static let hex00979d: UInt32 = 0x00979dff
  private static let hex434f54: UInt32 = 0x434f54ff
  private static let hex728e00: UInt32 = 0x728e00ff
  private static let hex7f8c8d: UInt32 = 0x7f8c8dff
  private static let hex8a7b52: UInt32 = 0x8a7b52ff
  private static let hex95a5a6: UInt32 = 0x95a5a6ff
  private static let hexa61717: UInt32 = 0xa61717ff
  private static let hexd35400: UInt32 = 0xd35400ff
  private static let hexffffff: UInt32 = 0xffffffff

  public func getBgColor() -> Color { Color(rgba: Self.hexffffff) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hex95a5a6), bg: Color(rgba: Self.hexffffff)),
      .commentPreproc: TextFormat(fg: Color(rgba: Self.hex728e00), bg: Color(rgba: Self.hexffffff)),
      .error: TextFormat(fg: Color(rgba: Self.hexa61717), bg: Color(rgba: Self.hexffffff)),
      .keyword: TextFormat(fg: Color(rgba: Self.hex728e00), bg: Color(rgba: Self.hexffffff)),
      .keywordConstant: TextFormat(fg: Color(rgba: Self.hex00979d), bg: Color(rgba: Self.hexffffff)),
      .keywordPseudo: TextFormat(fg: Color(rgba: Self.hex00979d), bg: Color(rgba: Self.hexffffff)),
      .keywordReserved: TextFormat(fg: Color(rgba: Self.hex00979d), bg: Color(rgba: Self.hexffffff)),
      .keywordType: TextFormat(fg: Color(rgba: Self.hex00979d), bg: Color(rgba: Self.hexffffff)),
      .name: TextFormat(fg: Color(rgba: Self.hex434f54), bg: Color(rgba: Self.hexffffff)),
      .nameBuiltin: TextFormat(fg: Color(rgba: Self.hex728e00), bg: Color(rgba: Self.hexffffff)),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hexd35400), bg: Color(rgba: Self.hexffffff)),
      .nameOther: TextFormat(fg: Color(rgba: Self.hex728e00), bg: Color(rgba: Self.hexffffff)),
      .number: TextFormat(fg: Color(rgba: Self.hex8a7b52), bg: Color(rgba: Self.hexffffff)),
      .operator: TextFormat(fg: Color(rgba: Self.hex728e00), bg: Color(rgba: Self.hexffffff)),
      .string: TextFormat(fg: Color(rgba: Self.hex7f8c8d), bg: Color(rgba: Self.hexffffff)),
    ]
  }
}
