// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "arduino" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct ArduinoTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#ffffff")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#95a5a6")!, bg: Color(fromHex: "#ffffff")!),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#728e00")!, bg: Color(fromHex: "#ffffff")!),
      .error: TextFormat(fg: Color(fromHex: "#a61717")!, bg: Color(fromHex: "#ffffff")!),
      .keyword: TextFormat(fg: Color(fromHex: "#728e00")!, bg: Color(fromHex: "#ffffff")!),
      .keywordConstant: TextFormat(fg: Color(fromHex: "#00979d")!, bg: Color(fromHex: "#ffffff")!),
      .keywordPseudo: TextFormat(fg: Color(fromHex: "#00979d")!, bg: Color(fromHex: "#ffffff")!),
      .keywordReserved: TextFormat(fg: Color(fromHex: "#00979d")!, bg: Color(fromHex: "#ffffff")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#00979d")!, bg: Color(fromHex: "#ffffff")!),
      .name: TextFormat(fg: Color(fromHex: "#434f54")!, bg: Color(fromHex: "#ffffff")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#728e00")!, bg: Color(fromHex: "#ffffff")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#d35400")!, bg: Color(fromHex: "#ffffff")!),
      .nameOther: TextFormat(fg: Color(fromHex: "#728e00")!, bg: Color(fromHex: "#ffffff")!),
      .number: TextFormat(fg: Color(fromHex: "#8a7b52")!, bg: Color(fromHex: "#ffffff")!),
      .operator: TextFormat(fg: Color(fromHex: "#728e00")!, bg: Color(fromHex: "#ffffff")!),
      .string: TextFormat(fg: Color(fromHex: "#7f8c8d")!, bg: Color(fromHex: "#ffffff")!),
    ]
  }
}
