// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "autumn" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct AutumnTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#ffffff")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#aaa")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#4c8317")!, bg: Color(fromHex: "#ffffff")!),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#00a")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#faa")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#a00")!, bg: Color(fromHex: "#ffffff")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#a00")!, bg: Color(fromHex: "#ffffff")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#0a0")!, bg: Color(fromHex: "#ffffff")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#ffffff")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#555")!, bg: Color(fromHex: "#ffffff")!),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#800080")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#a00")!, bg: Color(fromHex: "#ffffff")!),
      .keyword: TextFormat(fg: Color(fromHex: "#00a")!, bg: Color(fromHex: "#ffffff")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#0aa")!, bg: Color(fromHex: "#ffffff")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#1e90ff")!, bg: Color(fromHex: "#ffffff")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#0aa")!, bg: Color(fromHex: "#ffffff")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#0a0")!, bg: Color(fromHex: "#ffffff")!, underline: true),
      .nameConstant: TextFormat(fg: Color(fromHex: "#a00")!, bg: Color(fromHex: "#ffffff")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#ffffff")!),
      .nameEntity: TextFormat(fg: Color(fromHex: "#800")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameFunction: TextFormat(fg: Color(fromHex: "#0a0")!, bg: Color(fromHex: "#ffffff")!),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#0aa")!, bg: Color(fromHex: "#ffffff")!, underline: true),
      .nameTag: TextFormat(fg: Color(fromHex: "#1e90ff")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameVariable: TextFormat(fg: Color(fromHex: "#a00")!, bg: Color(fromHex: "#ffffff")!),
      .number: TextFormat(fg: Color(fromHex: "#099")!, bg: Color(fromHex: "#ffffff")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#00a")!, bg: Color(fromHex: "#ffffff")!),
      .string: TextFormat(fg: Color(fromHex: "#a50")!, bg: Color(fromHex: "#ffffff")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#099")!, bg: Color(fromHex: "#ffffff")!),
      .stringSymbol: TextFormat(fg: Color(fromHex: "#00a")!, bg: Color(fromHex: "#ffffff")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#bbb")!, bg: Color(fromHex: "#ffffff")!),
    ]
  }
}
