// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "borland" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct BorlandTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#ffffff")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#080")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#008080")!, bg: Color(fromHex: "#ffffff")!),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#080")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .error: TextFormat(fg: Color(fromHex: "#a61717")!, bg: Color(fromHex: "#e3d2d2")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#fdd")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#a00")!, bg: Color(fromHex: "#ffffff")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#999")!, bg: Color(fromHex: "#ffffff")!),
      .genericInserted: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#dfd")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#ffffff")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#555")!, bg: Color(fromHex: "#ffffff")!),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#aaa")!, bg: Color(fromHex: "#ffffff")!),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#a00")!, bg: Color(fromHex: "#ffffff")!),
      .keyword: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#ffffff")!),
      .nameTag: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .number: TextFormat(fg: Color(fromHex: "#00f")!, bg: Color(fromHex: "#ffffff")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .string: TextFormat(fg: Color(fromHex: "#00f")!, bg: Color(fromHex: "#ffffff")!),
      .stringChar: TextFormat(fg: Color(fromHex: "#800080")!, bg: Color(fromHex: "#ffffff")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#bbb")!, bg: Color(fromHex: "#ffffff")!)
    ]
  }
}
