// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "coffee" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct CoffeeTheme: CodeTheme {
  public init() {}

  private static let hex262220: UInt32 = 0x262220ff
  private static let hex70757a: UInt32 = 0x70757aff
  private static let hex849155: UInt32 = 0x849155ff
  private static let hex875f5f: UInt32 = 0x875f5fff
  private static let hex877575: UInt32 = 0x877575ff
  private static let hex878787: UInt32 = 0x878787ff
  private static let hex87afaf: UInt32 = 0x87afafff
  private static let hex8f9f9f: UInt32 = 0x8f9f9fff
  private static let hex919191: UInt32 = 0x919191ff
  private static let hexaf5f5f: UInt32 = 0xaf5f5fff
  private static let hexaf875f: UInt32 = 0xaf875fff
  private static let hexaf8787: UInt32 = 0xaf8787ff
  private static let hexb46276: UInt32 = 0xb46276ff
  private static let hexbb6868: UInt32 = 0xbb6868ff
  private static let hexc9b98f: UInt32 = 0xc9b98fff
  private static let hexddd0c0: UInt32 = 0xddd0c0ff
  private static let hexdfaf87: UInt32 = 0xdfaf87ff
  private static let hexfdd0c0: UInt32 = 0xfdd0c0ff

  public func getBgColor() -> Color { Color(rgba: Self.hex262220) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hexddd0c0), bg: Color(rgba: Self.hex262220)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hex70757a), bg: Color(rgba: Self.hex262220)),
      .commentHashbang: TextFormat(fg: Color(rgba: Self.hex8f9f9f), bg: Color(rgba: Self.hex262220)),
      .commentPreproc: TextFormat(fg: Color(rgba: Self.hexfdd0c0), bg: Color(rgba: Self.hex262220)),
      .commentPreprocFile: TextFormat(fg: Color(rgba: Self.hexc9b98f), bg: Color(rgba: Self.hex262220)),
      .commentSpecial: TextFormat(fg: Color(rgba: Self.hexaf5f5f), bg: Color(rgba: Self.hex262220)),
      .error: TextFormat(fg: Color(rgba: Self.hexaf5f5f), bg: Color(rgba: Self.hex262220)),
      .genericDeleted: TextFormat(fg: Color(rgba: Self.hexbb6868), bg: Color(rgba: Self.hex262220)),
      .genericEmph: TextFormat(fg: Color(rgba: Self.hexddd0c0), bg: Color(rgba: Self.hex262220), italic: true),
      .genericError: TextFormat(fg: Color(rgba: Self.hexaf5f5f), bg: Color(rgba: Self.hex262220)),
      .genericInserted: TextFormat(fg: Color(rgba: Self.hex849155), bg: Color(rgba: Self.hex262220)),
      .genericStrong: TextFormat(fg: Color(rgba: Self.hexddd0c0), bg: Color(rgba: Self.hex262220), bold: true),
      .genericTraceback: TextFormat(fg: Color(rgba: Self.hexaf5f5f), bg: Color(rgba: Self.hex262220)),
      .keyword: TextFormat(fg: Color(rgba: Self.hex919191), bg: Color(rgba: Self.hex262220)),
      .keywordConstant: TextFormat(fg: Color(rgba: Self.hex875f5f), bg: Color(rgba: Self.hex262220)),
      .keywordDeclaration: TextFormat(fg: Color(rgba: Self.hex875f5f), bg: Color(rgba: Self.hex262220)),
      .keywordNamespace: TextFormat(fg: Color(rgba: Self.hex875f5f), bg: Color(rgba: Self.hex262220)),
      .keywordReserved: TextFormat(fg: Color(rgba: Self.hexb46276), bg: Color(rgba: Self.hex262220)),
      .keywordType: TextFormat(fg: Color(rgba: Self.hexaf875f), bg: Color(rgba: Self.hex262220)),
      .literal: TextFormat(fg: Color(rgba: Self.hexaf875f), bg: Color(rgba: Self.hex262220)),
      .nameBuiltinPseudo: TextFormat(fg: Color(rgba: Self.hex87afaf), bg: Color(rgba: Self.hex262220)),
      .nameClass: TextFormat(fg: Color(rgba: Self.hex875f5f), bg: Color(rgba: Self.hex262220)),
      .nameConstant: TextFormat(fg: Color(rgba: Self.hexaf8787), bg: Color(rgba: Self.hex262220)),
      .nameDecorator: TextFormat(fg: Color(rgba: Self.hexfdd0c0), bg: Color(rgba: Self.hex262220)),
      .nameException: TextFormat(fg: Color(rgba: Self.hex877575), bg: Color(rgba: Self.hex262220)),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hexfdd0c0), bg: Color(rgba: Self.hex262220)),
      .nameProperty: TextFormat(fg: Color(rgba: Self.hexdfaf87), bg: Color(rgba: Self.hex262220)),
      .nameTag: TextFormat(fg: Color(rgba: Self.hex87afaf), bg: Color(rgba: Self.hex262220)),
      .number: TextFormat(fg: Color(rgba: Self.hex87afaf), bg: Color(rgba: Self.hex262220)),
      .operator: TextFormat(fg: Color(rgba: Self.hex878787), bg: Color(rgba: Self.hex262220)),
      .string: TextFormat(fg: Color(rgba: Self.hexc9b98f), bg: Color(rgba: Self.hex262220)),
      .stringAffix: TextFormat(fg: Color(rgba: Self.hexdfaf87), bg: Color(rgba: Self.hex262220)),
      .stringDoc: TextFormat(fg: Color(rgba: Self.hex878787), bg: Color(rgba: Self.hex262220)),
      .stringEscape: TextFormat(fg: Color(rgba: Self.hexaf5f5f), bg: Color(rgba: Self.hex262220)),
      .stringInterpol: TextFormat(fg: Color(rgba: Self.hexaf5f5f), bg: Color(rgba: Self.hex262220)),
      .stringOther: TextFormat(fg: Color(rgba: Self.hexfdd0c0), bg: Color(rgba: Self.hex262220)),
      .stringRegex: TextFormat(fg: Color(rgba: Self.hexaf5f5f), bg: Color(rgba: Self.hex262220)),
      .stringSymbol: TextFormat(fg: Color(rgba: Self.hexaf5f5f), bg: Color(rgba: Self.hex262220)),
    ]
  }
}
