// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "coffee" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct CoffeeTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#262220")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#ddd0c0")!, bg: Color(fromHex: "#262220")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#70757a")!, bg: Color(fromHex: "#262220")!),
      .commentHashbang: TextFormat(fg: Color(fromHex: "#8f9f9f")!, bg: Color(fromHex: "#262220")!),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#fdd0c0")!, bg: Color(fromHex: "#262220")!),
      .commentPreprocFile: TextFormat(fg: Color(fromHex: "#c9b98f")!, bg: Color(fromHex: "#262220")!),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#af5f5f")!, bg: Color(fromHex: "#262220")!),
      .error: TextFormat(fg: Color(fromHex: "#af5f5f")!, bg: Color(fromHex: "#262220")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#bb6868")!, bg: Color(fromHex: "#262220")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#ddd0c0")!, bg: Color(fromHex: "#262220")!, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#af5f5f")!, bg: Color(fromHex: "#262220")!),
      .genericInserted: TextFormat(fg: Color(fromHex: "#849155")!, bg: Color(fromHex: "#262220")!),
      .genericStrong: TextFormat(fg: Color(fromHex: "#ddd0c0")!, bg: Color(fromHex: "#262220")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#af5f5f")!, bg: Color(fromHex: "#262220")!),
      .keyword: TextFormat(fg: Color(fromHex: "#919191")!, bg: Color(fromHex: "#262220")!),
      .keywordConstant: TextFormat(fg: Color(fromHex: "#875f5f")!, bg: Color(fromHex: "#262220")!),
      .keywordDeclaration: TextFormat(fg: Color(fromHex: "#875f5f")!, bg: Color(fromHex: "#262220")!),
      .keywordNamespace: TextFormat(fg: Color(fromHex: "#875f5f")!, bg: Color(fromHex: "#262220")!),
      .keywordReserved: TextFormat(fg: Color(fromHex: "#b46276")!, bg: Color(fromHex: "#262220")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#af875f")!, bg: Color(fromHex: "#262220")!),
      .literal: TextFormat(fg: Color(fromHex: "#af875f")!, bg: Color(fromHex: "#262220")!),
      .nameBuiltinPseudo: TextFormat(fg: Color(fromHex: "#87afaf")!, bg: Color(fromHex: "#262220")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#875f5f")!, bg: Color(fromHex: "#262220")!),
      .nameConstant: TextFormat(fg: Color(fromHex: "#af8787")!, bg: Color(fromHex: "#262220")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#fdd0c0")!, bg: Color(fromHex: "#262220")!),
      .nameException: TextFormat(fg: Color(fromHex: "#877575")!, bg: Color(fromHex: "#262220")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#fdd0c0")!, bg: Color(fromHex: "#262220")!),
      .nameProperty: TextFormat(fg: Color(fromHex: "#dfaf87")!, bg: Color(fromHex: "#262220")!),
      .nameTag: TextFormat(fg: Color(fromHex: "#87afaf")!, bg: Color(fromHex: "#262220")!),
      .number: TextFormat(fg: Color(fromHex: "#87afaf")!, bg: Color(fromHex: "#262220")!),
      .operator: TextFormat(fg: Color(fromHex: "#878787")!, bg: Color(fromHex: "#262220")!),
      .string: TextFormat(fg: Color(fromHex: "#c9b98f")!, bg: Color(fromHex: "#262220")!),
      .stringAffix: TextFormat(fg: Color(fromHex: "#dfaf87")!, bg: Color(fromHex: "#262220")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#878787")!, bg: Color(fromHex: "#262220")!),
      .stringEscape: TextFormat(fg: Color(fromHex: "#af5f5f")!, bg: Color(fromHex: "#262220")!),
      .stringInterpol: TextFormat(fg: Color(fromHex: "#af5f5f")!, bg: Color(fromHex: "#262220")!),
      .stringOther: TextFormat(fg: Color(fromHex: "#fdd0c0")!, bg: Color(fromHex: "#262220")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#af5f5f")!, bg: Color(fromHex: "#262220")!),
      .stringSymbol: TextFormat(fg: Color(fromHex: "#af5f5f")!, bg: Color(fromHex: "#262220")!),
    ]
  }
}
