// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "colorful" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct ColorfulTheme: CodeTheme {
  public init() {}

  private static let hex000: UInt32 = 0x000ff
  private static let hex000000: UInt32 = 0x000000ff
  private static let hex000080: UInt32 = 0x000080ff
  private static let hex007020: UInt32 = 0x007020ff
  private static let hex00a000: UInt32 = 0x00a000ff
  private static let hex00c: UInt32 = 0x00cff
  private static let hex00d: UInt32 = 0x00dff
  private static let hex036: UInt32 = 0x036ff
  private static let hex038: UInt32 = 0x038ff
  private static let hex04d: UInt32 = 0x04dff
  private static let hex058: UInt32 = 0x058ff
  private static let hex06b: UInt32 = 0x06bff
  private static let hex070: UInt32 = 0x070ff
  private static let hex080: UInt32 = 0x080ff
  private static let hex0e84b5: UInt32 = 0x0e84b5ff
  private static let hex333: UInt32 = 0x333ff
  private static let hex339: UInt32 = 0x339ff
  private static let hex33b: UInt32 = 0x33bff
  private static let hex369: UInt32 = 0x369ff
  private static let hex40e: UInt32 = 0x40eff
  private static let hex555: UInt32 = 0x555ff
  private static let hex579: UInt32 = 0x579ff
  private static let hex60e: UInt32 = 0x60eff
  private static let hex666: UInt32 = 0x666ff
  private static let hex800: UInt32 = 0x800ff
  private static let hex800080: UInt32 = 0x800080ff
  private static let hex888: UInt32 = 0x888ff
  private static let hex963: UInt32 = 0x963ff
  private static let hex970: UInt32 = 0x970ff
  private static let hexa00000: UInt32 = 0xa00000ff
  private static let hexa60: UInt32 = 0xa60ff
  private static let hexb06: UInt32 = 0xb06ff
  private static let hexbbb: UInt32 = 0xbbbff
  private static let hexc00: UInt32 = 0xc00ff
  private static let hexc65d09: UInt32 = 0xc65d09ff
  private static let hexd20: UInt32 = 0xd20ff
  private static let hexd42: UInt32 = 0xd42ff
  private static let hexd70: UInt32 = 0xd70ff
  private static let hexeee: UInt32 = 0xeeeff
  private static let hexf00: UInt32 = 0xf00ff
  private static let hexfaa: UInt32 = 0xfaaff
  private static let hexfff0f0: UInt32 = 0xfff0f0ff
  private static let hexfff0ff: UInt32 = 0xfff0ffff
  private static let hexffffff: UInt32 = 0xffffffff

  public func getBgColor() -> Color { Color(rgba: Self.hexffffff) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hex888), bg: Color(rgba: Self.hexffffff)),
      .commentPreproc: TextFormat(fg: Color(rgba: Self.hex579), bg: Color(rgba: Self.hexffffff)),
      .commentSpecial: TextFormat(fg: Color(rgba: Self.hexc00), bg: Color(rgba: Self.hexffffff), bold: true),
      .error: TextFormat(fg: Color(rgba: Self.hexf00), bg: Color(rgba: Self.hexfaa)),
      .genericDeleted: TextFormat(fg: Color(rgba: Self.hexa00000), bg: Color(rgba: Self.hexffffff)),
      .genericEmph: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), italic: true),
      .genericEmphStrong: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true, italic: true),
      .genericError: TextFormat(fg: Color(rgba: Self.hexf00), bg: Color(rgba: Self.hexffffff)),
      .genericHeading: TextFormat(fg: Color(rgba: Self.hex000080), bg: Color(rgba: Self.hexffffff), bold: true),
      .genericInserted: TextFormat(fg: Color(rgba: Self.hex00a000), bg: Color(rgba: Self.hexffffff)),
      .genericOutput: TextFormat(fg: Color(rgba: Self.hex888), bg: Color(rgba: Self.hexffffff)),
      .genericPrompt: TextFormat(fg: Color(rgba: Self.hexc65d09), bg: Color(rgba: Self.hexffffff), bold: true),
      .genericStrong: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true),
      .genericSubheading: TextFormat(fg: Color(rgba: Self.hex800080), bg: Color(rgba: Self.hexffffff), bold: true),
      .genericTraceback: TextFormat(fg: Color(rgba: Self.hex04d), bg: Color(rgba: Self.hexffffff)),
      .keyword: TextFormat(fg: Color(rgba: Self.hex080), bg: Color(rgba: Self.hexffffff), bold: true),
      .keywordPseudo: TextFormat(fg: Color(rgba: Self.hex038), bg: Color(rgba: Self.hexffffff), bold: true),
      .keywordType: TextFormat(fg: Color(rgba: Self.hex339), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameAttribute: TextFormat(fg: Color(rgba: Self.hex00c), bg: Color(rgba: Self.hexffffff)),
      .nameBuiltin: TextFormat(fg: Color(rgba: Self.hex007020), bg: Color(rgba: Self.hexffffff)),
      .nameClass: TextFormat(fg: Color(rgba: Self.hexb06), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameConstant: TextFormat(fg: Color(rgba: Self.hex036), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameDecorator: TextFormat(fg: Color(rgba: Self.hex555), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameEntity: TextFormat(fg: Color(rgba: Self.hex800), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameException: TextFormat(fg: Color(rgba: Self.hexf00), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hex06b), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameLabel: TextFormat(fg: Color(rgba: Self.hex970), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameNamespace: TextFormat(fg: Color(rgba: Self.hex0e84b5), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameTag: TextFormat(fg: Color(rgba: Self.hex070), bg: Color(rgba: Self.hexffffff)),
      .nameVariable: TextFormat(fg: Color(rgba: Self.hex963), bg: Color(rgba: Self.hexffffff)),
      .nameVariableClass: TextFormat(fg: Color(rgba: Self.hex369), bg: Color(rgba: Self.hexffffff)),
      .nameVariableGlobal: TextFormat(fg: Color(rgba: Self.hexd70), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameVariableInstance: TextFormat(fg: Color(rgba: Self.hex33b), bg: Color(rgba: Self.hexffffff)),
      .number: TextFormat(fg: Color(rgba: Self.hex60e), bg: Color(rgba: Self.hexffffff), bold: true),
      .numberHex: TextFormat(fg: Color(rgba: Self.hex058), bg: Color(rgba: Self.hexffffff), bold: true),
      .numberInteger: TextFormat(fg: Color(rgba: Self.hex00d), bg: Color(rgba: Self.hexffffff), bold: true),
      .numberOct: TextFormat(fg: Color(rgba: Self.hex40e), bg: Color(rgba: Self.hexffffff), bold: true),
      .operator: TextFormat(fg: Color(rgba: Self.hex333), bg: Color(rgba: Self.hexffffff)),
      .operatorWord: TextFormat(fg: Color(rgba: Self.hex000), bg: Color(rgba: Self.hexffffff), bold: true),
      .string: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexfff0f0)),
      .stringChar: TextFormat(fg: Color(rgba: Self.hex04d), bg: Color(rgba: Self.hexffffff)),
      .stringDoc: TextFormat(fg: Color(rgba: Self.hexd42), bg: Color(rgba: Self.hexffffff)),
      .stringEscape: TextFormat(fg: Color(rgba: Self.hex666), bg: Color(rgba: Self.hexfff0f0), bold: true),
      .stringInterpol: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexeee)),
      .stringOther: TextFormat(fg: Color(rgba: Self.hexd20), bg: Color(rgba: Self.hexfff0f0)),
      .stringRegex: TextFormat(fg: Color(rgba: Self.hex000), bg: Color(rgba: Self.hexfff0ff)),
      .stringSymbol: TextFormat(fg: Color(rgba: Self.hexa60), bg: Color(rgba: Self.hexffffff)),
      .whitespace: TextFormat(fg: Color(rgba: Self.hexbbb), bg: Color(rgba: Self.hexffffff)),
    ]
  }
}
