// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "colorful" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct ColorfulTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#ffffff")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#ffffff")!),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#579")!, bg: Color(fromHex: "#ffffff")!),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#c00")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .error: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#faa")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#a00000")!, bg: Color(fromHex: "#ffffff")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#ffffff")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#00a000")!, bg: Color(fromHex: "#ffffff")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#ffffff")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#c65d09")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#800080")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#04d")!, bg: Color(fromHex: "#ffffff")!),
      .keyword: TextFormat(fg: Color(fromHex: "#080")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .keywordPseudo: TextFormat(fg: Color(fromHex: "#038")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .keywordType: TextFormat(fg: Color(fromHex: "#339")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#00c")!, bg: Color(fromHex: "#ffffff")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#007020")!, bg: Color(fromHex: "#ffffff")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#b06")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameConstant: TextFormat(fg: Color(fromHex: "#036")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#555")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameEntity: TextFormat(fg: Color(fromHex: "#800")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameException: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameFunction: TextFormat(fg: Color(fromHex: "#06b")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameLabel: TextFormat(fg: Color(fromHex: "#970")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#0e84b5")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameTag: TextFormat(fg: Color(fromHex: "#070")!, bg: Color(fromHex: "#ffffff")!),
      .nameVariable: TextFormat(fg: Color(fromHex: "#963")!, bg: Color(fromHex: "#ffffff")!),
      .nameVariableClass: TextFormat(fg: Color(fromHex: "#369")!, bg: Color(fromHex: "#ffffff")!),
      .nameVariableGlobal: TextFormat(fg: Color(fromHex: "#d70")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameVariableInstance: TextFormat(fg: Color(fromHex: "#33b")!, bg: Color(fromHex: "#ffffff")!),
      .number: TextFormat(fg: Color(fromHex: "#60e")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .numberHex: TextFormat(fg: Color(fromHex: "#058")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .numberInteger: TextFormat(fg: Color(fromHex: "#00d")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .numberOct: TextFormat(fg: Color(fromHex: "#40e")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .operator: TextFormat(fg: Color(fromHex: "#333")!, bg: Color(fromHex: "#ffffff")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .string: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#fff0f0")!),
      .stringChar: TextFormat(fg: Color(fromHex: "#04d")!, bg: Color(fromHex: "#ffffff")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#d42")!, bg: Color(fromHex: "#ffffff")!),
      .stringEscape: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#fff0f0")!, bold: true),
      .stringInterpol: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#eee")!),
      .stringOther: TextFormat(fg: Color(fromHex: "#d20")!, bg: Color(fromHex: "#fff0f0")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#fff0ff")!),
      .stringSymbol: TextFormat(fg: Color(fromHex: "#a60")!, bg: Color(fromHex: "#ffffff")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#bbb")!, bg: Color(fromHex: "#ffffff")!)
    ]
  }
}
