// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "dracula" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct DraculaTheme: CodeTheme {
  public init() {}

  private static let hex000000: UInt32 = 0x000000ff
  private static let hex282a36: UInt32 = 0x282a36ff
  private static let hex44475a: UInt32 = 0x44475aff
  private static let hex50fa7b: UInt32 = 0x50fa7bff
  private static let hex6272a4: UInt32 = 0x6272a4ff
  private static let hex8b080b: UInt32 = 0x8b080bff
  private static let hex8be9fd: UInt32 = 0x8be9fdff
  private static let hexbd93f9: UInt32 = 0xbd93f9ff
  private static let hexf8f8f2: UInt32 = 0xf8f8f2ff
  private static let hexff79c6: UInt32 = 0xff79c6ff
  private static let hexffb86c: UInt32 = 0xffb86cff

  public func getBgColor() -> Color { Color(rgba: Self.hex282a36) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hex282a36)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hex6272a4), bg: Color(rgba: Self.hex282a36)),
      .commentPreproc: TextFormat(fg: Color(rgba: Self.hexff79c6), bg: Color(rgba: Self.hex282a36)),
      .error: TextFormat(fg: Color(rgba: Self.hexf8f8f2), bg: Color(rgba: Self.hex282a36)),
      .generic: TextFormat(fg: Color(rgba: Self.hexf8f8f2), bg: Color(rgba: Self.hex282a36)),
      .genericDeleted: TextFormat(fg: Color(rgba: Self.hex8b080b), bg: Color(rgba: Self.hex282a36)),
      .genericEmph: TextFormat(fg: Color(rgba: Self.hexf8f8f2), bg: Color(rgba: Self.hex282a36), underline: true),
      .genericEmphStrong: TextFormat(fg: Color(rgba: Self.hexf8f8f2), bg: Color(rgba: Self.hex282a36), underline: true),
      .genericHeading: TextFormat(fg: Color(rgba: Self.hexf8f8f2), bg: Color(rgba: Self.hex282a36), bold: true),
      .genericInserted: TextFormat(fg: Color(rgba: Self.hexf8f8f2), bg: Color(rgba: Self.hex282a36), bold: true),
      .genericOutput: TextFormat(fg: Color(rgba: Self.hex44475a), bg: Color(rgba: Self.hex282a36)),
      .genericSubheading: TextFormat(fg: Color(rgba: Self.hexf8f8f2), bg: Color(rgba: Self.hex282a36), bold: true),
      .keyword: TextFormat(fg: Color(rgba: Self.hexff79c6), bg: Color(rgba: Self.hex282a36)),
      .keywordDeclaration: TextFormat(fg: Color(rgba: Self.hex8be9fd), bg: Color(rgba: Self.hex282a36), italic: true),
      .keywordType: TextFormat(fg: Color(rgba: Self.hex8be9fd), bg: Color(rgba: Self.hex282a36)),
      .literal: TextFormat(fg: Color(rgba: Self.hexf8f8f2), bg: Color(rgba: Self.hex282a36)),
      .name: TextFormat(fg: Color(rgba: Self.hexf8f8f2), bg: Color(rgba: Self.hex282a36)),
      .nameAttribute: TextFormat(fg: Color(rgba: Self.hex50fa7b), bg: Color(rgba: Self.hex282a36)),
      .nameBuiltin: TextFormat(fg: Color(rgba: Self.hex8be9fd), bg: Color(rgba: Self.hex282a36), italic: true),
      .nameBuiltinPseudo: TextFormat(fg: Color(rgba: Self.hexf8f8f2), bg: Color(rgba: Self.hex282a36), italic: true),
      .nameClass: TextFormat(fg: Color(rgba: Self.hex50fa7b), bg: Color(rgba: Self.hex282a36)),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hex50fa7b), bg: Color(rgba: Self.hex282a36)),
      .nameLabel: TextFormat(fg: Color(rgba: Self.hex8be9fd), bg: Color(rgba: Self.hex282a36), italic: true),
      .nameTag: TextFormat(fg: Color(rgba: Self.hexff79c6), bg: Color(rgba: Self.hex282a36)),
      .nameVariable: TextFormat(fg: Color(rgba: Self.hex8be9fd), bg: Color(rgba: Self.hex282a36), italic: true),
      .number: TextFormat(fg: Color(rgba: Self.hexffb86c), bg: Color(rgba: Self.hex282a36)),
      .operator: TextFormat(fg: Color(rgba: Self.hexff79c6), bg: Color(rgba: Self.hex282a36)),
      .other: TextFormat(fg: Color(rgba: Self.hexf8f8f2), bg: Color(rgba: Self.hex282a36)),
      .punctuation: TextFormat(fg: Color(rgba: Self.hexf8f8f2), bg: Color(rgba: Self.hex282a36)),
      .string: TextFormat(fg: Color(rgba: Self.hexbd93f9), bg: Color(rgba: Self.hex282a36)),
      .whitespace: TextFormat(fg: Color(rgba: Self.hexf8f8f2), bg: Color(rgba: Self.hex282a36)),
    ]
  }
}
