// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "dracula" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct DraculaTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#282a36")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#282a36")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#6272a4")!, bg: Color(fromHex: "#282a36")!),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#ff79c6")!, bg: Color(fromHex: "#282a36")!),
      .error: TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#282a36")!),
      .generic: TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#282a36")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#8b080b")!, bg: Color(fromHex: "#282a36")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#282a36")!, underline: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#282a36")!, underline: true),
      .genericHeading: TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#282a36")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#282a36")!, bold: true),
      .genericOutput: TextFormat(fg: Color(fromHex: "#44475a")!, bg: Color(fromHex: "#282a36")!),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#282a36")!, bold: true),
      .keyword: TextFormat(fg: Color(fromHex: "#ff79c6")!, bg: Color(fromHex: "#282a36")!),
      .keywordDeclaration: TextFormat(fg: Color(fromHex: "#8be9fd")!, bg: Color(fromHex: "#282a36")!, italic: true),
      .keywordType: TextFormat(fg: Color(fromHex: "#8be9fd")!, bg: Color(fromHex: "#282a36")!),
      .literal: TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#282a36")!),
      .name: TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#282a36")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#50fa7b")!, bg: Color(fromHex: "#282a36")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#8be9fd")!, bg: Color(fromHex: "#282a36")!, italic: true),
      .nameBuiltinPseudo: TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#282a36")!, italic: true),
      .nameClass: TextFormat(fg: Color(fromHex: "#50fa7b")!, bg: Color(fromHex: "#282a36")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#50fa7b")!, bg: Color(fromHex: "#282a36")!),
      .nameLabel: TextFormat(fg: Color(fromHex: "#8be9fd")!, bg: Color(fromHex: "#282a36")!, italic: true),
      .nameTag: TextFormat(fg: Color(fromHex: "#ff79c6")!, bg: Color(fromHex: "#282a36")!),
      .nameVariable: TextFormat(fg: Color(fromHex: "#8be9fd")!, bg: Color(fromHex: "#282a36")!, italic: true),
      .number: TextFormat(fg: Color(fromHex: "#ffb86c")!, bg: Color(fromHex: "#282a36")!),
      .operator: TextFormat(fg: Color(fromHex: "#ff79c6")!, bg: Color(fromHex: "#282a36")!),
      .other: TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#282a36")!),
      .punctuation: TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#282a36")!),
      .string: TextFormat(fg: Color(fromHex: "#bd93f9")!, bg: Color(fromHex: "#282a36")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#282a36")!)
    ]
  }
}
