// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "emacs" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct EmacsTheme: CodeTheme {
  public init() {}

  private static let hex000000: UInt32 = 0x000000ff
  private static let hex000080: UInt32 = 0x000080ff
  private static let hex008000: UInt32 = 0x008000ff
  private static let hex00a000: UInt32 = 0x00a000ff
  private static let hex00f: UInt32 = 0x00fff
  private static let hex04d: UInt32 = 0x04dff
  private static let hex080: UInt32 = 0x080ff
  private static let hex0b0: UInt32 = 0x0b0ff
  private static let hex666: UInt32 = 0x666ff
  private static let hex800: UInt32 = 0x800ff
  private static let hex800080: UInt32 = 0x800080ff
  private static let hex888: UInt32 = 0x888ff
  private static let hex999: UInt32 = 0x999ff
  private static let hexa00000: UInt32 = 0xa00000ff
  private static let hexa0a000: UInt32 = 0xa0a000ff
  private static let hexa2f: UInt32 = 0xa2fff
  private static let hexb44: UInt32 = 0xb44ff
  private static let hexb62: UInt32 = 0xb62ff
  private static let hexb68: UInt32 = 0xb68ff
  private static let hexb8860b: UInt32 = 0xb8860bff
  private static let hexbbb: UInt32 = 0xbbbff
  private static let hexd2413a: UInt32 = 0xd2413aff
  private static let hexf00: UInt32 = 0xf00ff
  private static let hexf8f8f8: UInt32 = 0xf8f8f8ff

  public func getBgColor() -> Color { Color(rgba: Self.hexf8f8f8) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexf8f8f8)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hex080), bg: Color(rgba: Self.hexf8f8f8), italic: true),
      .commentPreproc: TextFormat(fg: Color(rgba: Self.hex080), bg: Color(rgba: Self.hexf8f8f8)),
      .commentSpecial: TextFormat(fg: Color(rgba: Self.hex080), bg: Color(rgba: Self.hexf8f8f8), bold: true),
      .genericDeleted: TextFormat(fg: Color(rgba: Self.hexa00000), bg: Color(rgba: Self.hexf8f8f8)),
      .genericEmph: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexf8f8f8), italic: true),
      .genericEmphStrong: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexf8f8f8), bold: true, italic: true),
      .genericError: TextFormat(fg: Color(rgba: Self.hexf00), bg: Color(rgba: Self.hexf8f8f8)),
      .genericHeading: TextFormat(fg: Color(rgba: Self.hex000080), bg: Color(rgba: Self.hexf8f8f8), bold: true),
      .genericInserted: TextFormat(fg: Color(rgba: Self.hex00a000), bg: Color(rgba: Self.hexf8f8f8)),
      .genericOutput: TextFormat(fg: Color(rgba: Self.hex888), bg: Color(rgba: Self.hexf8f8f8)),
      .genericPrompt: TextFormat(fg: Color(rgba: Self.hex000080), bg: Color(rgba: Self.hexf8f8f8), bold: true),
      .genericStrong: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexf8f8f8), bold: true),
      .genericSubheading: TextFormat(fg: Color(rgba: Self.hex800080), bg: Color(rgba: Self.hexf8f8f8), bold: true),
      .genericTraceback: TextFormat(fg: Color(rgba: Self.hex04d), bg: Color(rgba: Self.hexf8f8f8)),
      .keyword: TextFormat(fg: Color(rgba: Self.hexa2f), bg: Color(rgba: Self.hexf8f8f8), bold: true),
      .keywordPseudo: TextFormat(fg: Color(rgba: Self.hexa2f), bg: Color(rgba: Self.hexf8f8f8)),
      .keywordType: TextFormat(fg: Color(rgba: Self.hex0b0), bg: Color(rgba: Self.hexf8f8f8), bold: true),
      .nameAttribute: TextFormat(fg: Color(rgba: Self.hexb44), bg: Color(rgba: Self.hexf8f8f8)),
      .nameBuiltin: TextFormat(fg: Color(rgba: Self.hexa2f), bg: Color(rgba: Self.hexf8f8f8)),
      .nameClass: TextFormat(fg: Color(rgba: Self.hex00f), bg: Color(rgba: Self.hexf8f8f8)),
      .nameConstant: TextFormat(fg: Color(rgba: Self.hex800), bg: Color(rgba: Self.hexf8f8f8)),
      .nameDecorator: TextFormat(fg: Color(rgba: Self.hexa2f), bg: Color(rgba: Self.hexf8f8f8)),
      .nameEntity: TextFormat(fg: Color(rgba: Self.hex999), bg: Color(rgba: Self.hexf8f8f8), bold: true),
      .nameException: TextFormat(fg: Color(rgba: Self.hexd2413a), bg: Color(rgba: Self.hexf8f8f8), bold: true),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hex00a000), bg: Color(rgba: Self.hexf8f8f8)),
      .nameLabel: TextFormat(fg: Color(rgba: Self.hexa0a000), bg: Color(rgba: Self.hexf8f8f8)),
      .nameNamespace: TextFormat(fg: Color(rgba: Self.hex00f), bg: Color(rgba: Self.hexf8f8f8), bold: true),
      .nameTag: TextFormat(fg: Color(rgba: Self.hex008000), bg: Color(rgba: Self.hexf8f8f8), bold: true),
      .nameVariable: TextFormat(fg: Color(rgba: Self.hexb8860b), bg: Color(rgba: Self.hexf8f8f8)),
      .number: TextFormat(fg: Color(rgba: Self.hex666), bg: Color(rgba: Self.hexf8f8f8)),
      .operator: TextFormat(fg: Color(rgba: Self.hex666), bg: Color(rgba: Self.hexf8f8f8)),
      .operatorWord: TextFormat(fg: Color(rgba: Self.hexa2f), bg: Color(rgba: Self.hexf8f8f8), bold: true),
      .string: TextFormat(fg: Color(rgba: Self.hexb44), bg: Color(rgba: Self.hexf8f8f8)),
      .stringDoc: TextFormat(fg: Color(rgba: Self.hexb44), bg: Color(rgba: Self.hexf8f8f8), italic: true),
      .stringEscape: TextFormat(fg: Color(rgba: Self.hexb62), bg: Color(rgba: Self.hexf8f8f8), bold: true),
      .stringInterpol: TextFormat(fg: Color(rgba: Self.hexb68), bg: Color(rgba: Self.hexf8f8f8), bold: true),
      .stringOther: TextFormat(fg: Color(rgba: Self.hex008000), bg: Color(rgba: Self.hexf8f8f8)),
      .stringRegex: TextFormat(fg: Color(rgba: Self.hexb68), bg: Color(rgba: Self.hexf8f8f8)),
      .stringSymbol: TextFormat(fg: Color(rgba: Self.hexb8860b), bg: Color(rgba: Self.hexf8f8f8)),
      .whitespace: TextFormat(fg: Color(rgba: Self.hexbbb), bg: Color(rgba: Self.hexf8f8f8)),
    ]
  }
}
