// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "emacs" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct EmacsTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#f8f8f8")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f8f8f8")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#080")!, bg: Color(fromHex: "#f8f8f8")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#080")!, bg: Color(fromHex: "#f8f8f8")!),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#080")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#a00000")!, bg: Color(fromHex: "#f8f8f8")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f8f8f8")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f8f8f8")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#f8f8f8")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#00a000")!, bg: Color(fromHex: "#f8f8f8")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#f8f8f8")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#800080")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#04d")!, bg: Color(fromHex: "#f8f8f8")!),
      .keyword: TextFormat(fg: Color(fromHex: "#a2f")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .keywordPseudo: TextFormat(fg: Color(fromHex: "#a2f")!, bg: Color(fromHex: "#f8f8f8")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#0b0")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#b44")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#a2f")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#00f")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameConstant: TextFormat(fg: Color(fromHex: "#800")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#a2f")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameEntity: TextFormat(fg: Color(fromHex: "#999")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .nameException: TextFormat(fg: Color(fromHex: "#d2413a")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .nameFunction: TextFormat(fg: Color(fromHex: "#00a000")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameLabel: TextFormat(fg: Color(fromHex: "#a0a000")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#00f")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .nameTag: TextFormat(fg: Color(fromHex: "#008000")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .nameVariable: TextFormat(fg: Color(fromHex: "#b8860b")!, bg: Color(fromHex: "#f8f8f8")!),
      .number: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#f8f8f8")!),
      .operator: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#f8f8f8")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#a2f")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .string: TextFormat(fg: Color(fromHex: "#b44")!, bg: Color(fromHex: "#f8f8f8")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#b44")!, bg: Color(fromHex: "#f8f8f8")!, italic: true),
      .stringEscape: TextFormat(fg: Color(fromHex: "#b62")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .stringInterpol: TextFormat(fg: Color(fromHex: "#b68")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .stringOther: TextFormat(fg: Color(fromHex: "#008000")!, bg: Color(fromHex: "#f8f8f8")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#b68")!, bg: Color(fromHex: "#f8f8f8")!),
      .stringSymbol: TextFormat(fg: Color(fromHex: "#b8860b")!, bg: Color(fromHex: "#f8f8f8")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#bbb")!, bg: Color(fromHex: "#f8f8f8")!),
    ]
  }
}
