// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "friendly_grayscale" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct FriendlyGrayscaleTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#f0f0f0")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f0f0f0")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#959595")!, bg: Color(fromHex: "#f0f0f0")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#575757")!, bg: Color(fromHex: "#f0f0f0")!),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#959595")!, bg: Color(fromHex: "#f4f4f4")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#545454")!, bg: Color(fromHex: "#f0f0f0")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f0f0f0")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f0f0f0")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#898989")!, bg: Color(fromHex: "#f0f0f0")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#373737")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#7d7d7d")!, bg: Color(fromHex: "#f0f0f0")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#f0f0f0")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#7e7e7e")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#5a5a5a")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#6d6d6d")!, bg: Color(fromHex: "#f0f0f0")!),
      .keyword: TextFormat(fg: Color(fromHex: "#575757")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .keywordPseudo: TextFormat(fg: Color(fromHex: "#575757")!, bg: Color(fromHex: "#f0f0f0")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#4f4f4f")!, bg: Color(fromHex: "#f0f0f0")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#707070")!, bg: Color(fromHex: "#f0f0f0")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#575757")!, bg: Color(fromHex: "#f0f0f0")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#7e7e7e")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .nameConstant: TextFormat(fg: Color(fromHex: "#a5a5a5")!, bg: Color(fromHex: "#f0f0f0")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#555")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .nameEntity: TextFormat(fg: Color(fromHex: "#848484")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .nameException: TextFormat(fg: Color(fromHex: "#575757")!, bg: Color(fromHex: "#f0f0f0")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#3f3f3f")!, bg: Color(fromHex: "#f0f0f0")!),
      .nameLabel: TextFormat(fg: Color(fromHex: "#363636")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#7e7e7e")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .nameTag: TextFormat(fg: Color(fromHex: "#3b3b3b")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .nameVariable: TextFormat(fg: Color(fromHex: "#9a9a9a")!, bg: Color(fromHex: "#f0f0f0")!),
      .number: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#f0f0f0")!),
      .operator: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#f0f0f0")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#575757")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .string: TextFormat(fg: Color(fromHex: "#717171")!, bg: Color(fromHex: "#f0f0f0")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#717171")!, bg: Color(fromHex: "#f0f0f0")!, italic: true),
      .stringEscape: TextFormat(fg: Color(fromHex: "#717171")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .stringInterpol: TextFormat(fg: Color(fromHex: "#9f9f9f")!, bg: Color(fromHex: "#f0f0f0")!, italic: true),
      .stringOther: TextFormat(fg: Color(fromHex: "#7e7e7e")!, bg: Color(fromHex: "#f0f0f0")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#575757")!, bg: Color(fromHex: "#f0f0f0")!),
      .stringSymbol: TextFormat(fg: Color(fromHex: "#676767")!, bg: Color(fromHex: "#f0f0f0")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#bbb")!, bg: Color(fromHex: "#f0f0f0")!),
    ]
  }
}
