// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "friendly" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct FriendlyTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#f0f0f0")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f0f0f0")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#60a0b0")!, bg: Color(fromHex: "#f0f0f0")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#007020")!, bg: Color(fromHex: "#f0f0f0")!),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#60a0b0")!, bg: Color(fromHex: "#fff0f0")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#a00000")!, bg: Color(fromHex: "#f0f0f0")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f0f0f0")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f0f0f0")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#f0f0f0")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#00a000")!, bg: Color(fromHex: "#f0f0f0")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#f0f0f0")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#c65d09")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#800080")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#04d")!, bg: Color(fromHex: "#f0f0f0")!),
      .keyword: TextFormat(fg: Color(fromHex: "#007020")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .keywordPseudo: TextFormat(fg: Color(fromHex: "#007020")!, bg: Color(fromHex: "#f0f0f0")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#902000")!, bg: Color(fromHex: "#f0f0f0")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#4070a0")!, bg: Color(fromHex: "#f0f0f0")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#007020")!, bg: Color(fromHex: "#f0f0f0")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#0e84b5")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .nameConstant: TextFormat(fg: Color(fromHex: "#60add5")!, bg: Color(fromHex: "#f0f0f0")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#555")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .nameEntity: TextFormat(fg: Color(fromHex: "#d55537")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .nameException: TextFormat(fg: Color(fromHex: "#007020")!, bg: Color(fromHex: "#f0f0f0")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#06287e")!, bg: Color(fromHex: "#f0f0f0")!),
      .nameLabel: TextFormat(fg: Color(fromHex: "#002070")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#0e84b5")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .nameTag: TextFormat(fg: Color(fromHex: "#062873")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .nameVariable: TextFormat(fg: Color(fromHex: "#bb60d5")!, bg: Color(fromHex: "#f0f0f0")!),
      .number: TextFormat(fg: Color(fromHex: "#40a070")!, bg: Color(fromHex: "#f0f0f0")!),
      .operator: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#f0f0f0")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#007020")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .string: TextFormat(fg: Color(fromHex: "#4070a0")!, bg: Color(fromHex: "#f0f0f0")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#4070a0")!, bg: Color(fromHex: "#f0f0f0")!, italic: true),
      .stringEscape: TextFormat(fg: Color(fromHex: "#4070a0")!, bg: Color(fromHex: "#f0f0f0")!, bold: true),
      .stringInterpol: TextFormat(fg: Color(fromHex: "#70a0d0")!, bg: Color(fromHex: "#f0f0f0")!, italic: true),
      .stringOther: TextFormat(fg: Color(fromHex: "#c65d09")!, bg: Color(fromHex: "#f0f0f0")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#235388")!, bg: Color(fromHex: "#f0f0f0")!),
      .stringSymbol: TextFormat(fg: Color(fromHex: "#517918")!, bg: Color(fromHex: "#f0f0f0")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#bbb")!, bg: Color(fromHex: "#f0f0f0")!),
    ]
  }
}
