// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "fruity" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct FruityTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#111111")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#ffffff")!, bg: Color(fromHex: "#111111")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#080")!, bg: Color(fromHex: "#0f140f")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#ff0007")!, bg: Color(fromHex: "#0f140f")!, bold: true, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#111111")!),
      .escape: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#111111")!),
      .generic: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#111111")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#111111")!, bold: true),
      .genericOutput: TextFormat(fg: Color(fromHex: "#444")!, bg: Color(fromHex: "#222")!),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#111111")!, bold: true),
      .keyword: TextFormat(fg: Color(fromHex: "#fb660a")!, bg: Color(fromHex: "#111111")!, bold: true),
      .keywordPseudo: TextFormat(fg: Color(fromHex: "#fb660a")!, bg: Color(fromHex: "#111111")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#cdcaa9")!, bg: Color(fromHex: "#111111")!, bold: true),
      .literal: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#111111")!),
      .name: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#111111")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#ff0086")!, bg: Color(fromHex: "#111111")!, bold: true),
      .nameConstant: TextFormat(fg: Color(fromHex: "#0086d2")!, bg: Color(fromHex: "#111111")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#ff0086")!, bg: Color(fromHex: "#111111")!, bold: true),
      .nameTag: TextFormat(fg: Color(fromHex: "#fb660a")!, bg: Color(fromHex: "#111111")!, bold: true),
      .nameVariable: TextFormat(fg: Color(fromHex: "#fb660a")!, bg: Color(fromHex: "#111111")!),
      .number: TextFormat(fg: Color(fromHex: "#0086f7")!, bg: Color(fromHex: "#111111")!, bold: true),
      .operator: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#111111")!),
      .other: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#111111")!),
      .punctuation: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#111111")!),
      .string: TextFormat(fg: Color(fromHex: "#0086d2")!, bg: Color(fromHex: "#111111")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#111111")!),
    ]
  }
}
