// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "github-dark" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct GithubDarkTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#0d1117")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#e6edf3")!, bg: Color(fromHex: "#0d1117")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#8b949e")!, bg: Color(fromHex: "#0d1117")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#8b949e")!, bg: Color(fromHex: "#0d1117")!, bold: true, italic: true),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#8b949e")!, bg: Color(fromHex: "#0d1117")!, bold: true, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#f85149")!, bg: Color(fromHex: "#0d1117")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#ffa198")!, bg: Color(fromHex: "#490202")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#e6edf3")!, bg: Color(fromHex: "#0d1117")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#e6edf3")!, bg: Color(fromHex: "#0d1117")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#ffa198")!, bg: Color(fromHex: "#0d1117")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#79c0ff")!, bg: Color(fromHex: "#0d1117")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#56d364")!, bg: Color(fromHex: "#0f5323")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#8b949e")!, bg: Color(fromHex: "#0d1117")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#8b949e")!, bg: Color(fromHex: "#0d1117")!),
      .genericStrong: TextFormat(fg: Color(fromHex: "#e6edf3")!, bg: Color(fromHex: "#0d1117")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#79c0ff")!, bg: Color(fromHex: "#0d1117")!),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#ff7b72")!, bg: Color(fromHex: "#0d1117")!),
      .keyword: TextFormat(fg: Color(fromHex: "#ff7b72")!, bg: Color(fromHex: "#0d1117")!),
      .keywordConstant: TextFormat(fg: Color(fromHex: "#79c0ff")!, bg: Color(fromHex: "#0d1117")!),
      .keywordPseudo: TextFormat(fg: Color(fromHex: "#79c0ff")!, bg: Color(fromHex: "#0d1117")!),
      .literal: TextFormat(fg: Color(fromHex: "#a5d6ff")!, bg: Color(fromHex: "#0d1117")!),
      .literalDate: TextFormat(fg: Color(fromHex: "#79c0ff")!, bg: Color(fromHex: "#0d1117")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#f0883e")!, bg: Color(fromHex: "#0d1117")!, bold: true),
      .nameConstant: TextFormat(fg: Color(fromHex: "#79c0ff")!, bg: Color(fromHex: "#0d1117")!, bold: true),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#d2a8ff")!, bg: Color(fromHex: "#0d1117")!, bold: true),
      .nameEntity: TextFormat(fg: Color(fromHex: "#ffa657")!, bg: Color(fromHex: "#0d1117")!),
      .nameException: TextFormat(fg: Color(fromHex: "#f0883e")!, bg: Color(fromHex: "#0d1117")!, bold: true),
      .nameFunction: TextFormat(fg: Color(fromHex: "#d2a8ff")!, bg: Color(fromHex: "#0d1117")!, bold: true),
      .nameLabel: TextFormat(fg: Color(fromHex: "#79c0ff")!, bg: Color(fromHex: "#0d1117")!, bold: true),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#ff7b72")!, bg: Color(fromHex: "#0d1117")!),
      .nameProperty: TextFormat(fg: Color(fromHex: "#79c0ff")!, bg: Color(fromHex: "#0d1117")!),
      .nameTag: TextFormat(fg: Color(fromHex: "#7ee787")!, bg: Color(fromHex: "#0d1117")!),
      .nameVariable: TextFormat(fg: Color(fromHex: "#79c0ff")!, bg: Color(fromHex: "#0d1117")!),
      .operator: TextFormat(fg: Color(fromHex: "#ff7b72")!, bg: Color(fromHex: "#0d1117")!, bold: true),
      .stringAffix: TextFormat(fg: Color(fromHex: "#79c0ff")!, bg: Color(fromHex: "#0d1117")!),
      .stringDelimiter: TextFormat(fg: Color(fromHex: "#79c0ff")!, bg: Color(fromHex: "#0d1117")!),
      .stringEscape: TextFormat(fg: Color(fromHex: "#79c0ff")!, bg: Color(fromHex: "#0d1117")!),
      .stringHeredoc: TextFormat(fg: Color(fromHex: "#79c0ff")!, bg: Color(fromHex: "#0d1117")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#79c0ff")!, bg: Color(fromHex: "#0d1117")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#6e7681")!, bg: Color(fromHex: "#0d1117")!),
    ]
  }
}
