// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "gruvbox-light" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct GruvboxLightTheme: CodeTheme {
  public init() {}

  private static let hex000000: UInt32 = 0x000000ff
  private static let hex076678: UInt32 = 0x076678ff
  private static let hex32302f: UInt32 = 0x32302fff
  private static let hex3c3836: UInt32 = 0x3c3836ff
  private static let hex427b58: UInt32 = 0x427b58ff
  private static let hex79740e: UInt32 = 0x79740eff
  private static let hex7c6f64: UInt32 = 0x7c6f64ff
  private static let hex8f3f71: UInt32 = 0x8f3f71ff
  private static let hex928374: UInt32 = 0x928374ff
  private static let hex9d0006: UInt32 = 0x9d0006ff
  private static let hexaf3a03: UInt32 = 0xaf3a03ff
  private static let hexb57614: UInt32 = 0xb57614ff
  private static let hexfbf1c7: UInt32 = 0xfbf1c7ff

  public func getBgColor() -> Color { Color(rgba: Self.hexfbf1c7) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexfbf1c7)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hex928374), bg: Color(rgba: Self.hexfbf1c7), italic: true),
      .commentSpecial: TextFormat(fg: Color(rgba: Self.hex3c3836), bg: Color(rgba: Self.hexfbf1c7), bold: true, italic: true),
      .error: TextFormat(fg: Color(rgba: Self.hexfbf1c7), bg: Color(rgba: Self.hex9d0006)),
      .genericDeleted: TextFormat(fg: Color(rgba: Self.hexfbf1c7), bg: Color(rgba: Self.hex9d0006)),
      .genericEmph: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexfbf1c7), italic: true),
      .genericError: TextFormat(fg: Color(rgba: Self.hex9d0006), bg: Color(rgba: Self.hexfbf1c7)),
      .genericHeading: TextFormat(fg: Color(rgba: Self.hex3c3836), bg: Color(rgba: Self.hexfbf1c7), bold: true),
      .genericInserted: TextFormat(fg: Color(rgba: Self.hexfbf1c7), bg: Color(rgba: Self.hex79740e)),
      .genericOutput: TextFormat(fg: Color(rgba: Self.hex32302f), bg: Color(rgba: Self.hexfbf1c7)),
      .genericPrompt: TextFormat(fg: Color(rgba: Self.hex7c6f64), bg: Color(rgba: Self.hexfbf1c7)),
      .genericStrong: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexfbf1c7), bold: true),
      .genericSubheading: TextFormat(fg: Color(rgba: Self.hex3c3836), bg: Color(rgba: Self.hexfbf1c7), underline: true),
      .genericTraceback: TextFormat(fg: Color(rgba: Self.hex9d0006), bg: Color(rgba: Self.hexfbf1c7)),
      .keyword: TextFormat(fg: Color(rgba: Self.hex9d0006), bg: Color(rgba: Self.hexfbf1c7)),
      .nameAttribute: TextFormat(fg: Color(rgba: Self.hexb57614), bg: Color(rgba: Self.hexfbf1c7)),
      .nameBuiltin: TextFormat(fg: Color(rgba: Self.hexaf3a03), bg: Color(rgba: Self.hexfbf1c7)),
      .nameClass: TextFormat(fg: Color(rgba: Self.hex427b58), bg: Color(rgba: Self.hexfbf1c7)),
      .nameConstant: TextFormat(fg: Color(rgba: Self.hex8f3f71), bg: Color(rgba: Self.hexfbf1c7)),
      .nameDecorator: TextFormat(fg: Color(rgba: Self.hex9d0006), bg: Color(rgba: Self.hexfbf1c7)),
      .nameException: TextFormat(fg: Color(rgba: Self.hex9d0006), bg: Color(rgba: Self.hexfbf1c7)),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hex427b58), bg: Color(rgba: Self.hexfbf1c7)),
      .nameNamespace: TextFormat(fg: Color(rgba: Self.hex427b58), bg: Color(rgba: Self.hexfbf1c7)),
      .nameTag: TextFormat(fg: Color(rgba: Self.hex427b58), bg: Color(rgba: Self.hexfbf1c7)),
      .nameVariable: TextFormat(fg: Color(rgba: Self.hex076678), bg: Color(rgba: Self.hexfbf1c7)),
      .number: TextFormat(fg: Color(rgba: Self.hex8f3f71), bg: Color(rgba: Self.hexfbf1c7)),
      .operatorWord: TextFormat(fg: Color(rgba: Self.hex9d0006), bg: Color(rgba: Self.hexfbf1c7)),
      .string: TextFormat(fg: Color(rgba: Self.hex79740e), bg: Color(rgba: Self.hexfbf1c7)),
      .stringEscape: TextFormat(fg: Color(rgba: Self.hexaf3a03), bg: Color(rgba: Self.hexfbf1c7)),
    ]
  }
}
