// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "gruvbox-dark" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct GruvboxDarkTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#282828")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#dddddd")!, bg: Color(fromHex: "#282828")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#928374")!, bg: Color(fromHex: "#282828")!, italic: true),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#ebdbb2")!, bg: Color(fromHex: "#282828")!, bold: true, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#282828")!, bg: Color(fromHex: "#fb4934")!),
      .escape: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#282828")!),
      .generic: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#282828")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#282828")!, bg: Color(fromHex: "#fb4934")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#282828")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#282828")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#fb4934")!, bg: Color(fromHex: "#282828")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#ebdbb2")!, bg: Color(fromHex: "#282828")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#282828")!, bg: Color(fromHex: "#b8bb26")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#f2e5bc")!, bg: Color(fromHex: "#282828")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#a89984")!, bg: Color(fromHex: "#282828")!),
      .genericStrong: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#282828")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#ebdbb2")!, bg: Color(fromHex: "#282828")!, underline: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#fb4934")!, bg: Color(fromHex: "#282828")!),
      .keyword: TextFormat(fg: Color(fromHex: "#fb4934")!, bg: Color(fromHex: "#282828")!),
      .literal: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#282828")!),
      .name: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#282828")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#fabd2f")!, bg: Color(fromHex: "#282828")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#fe8019")!, bg: Color(fromHex: "#282828")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#8ec07c")!, bg: Color(fromHex: "#282828")!),
      .nameConstant: TextFormat(fg: Color(fromHex: "#d3869b")!, bg: Color(fromHex: "#282828")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#fb4934")!, bg: Color(fromHex: "#282828")!),
      .nameException: TextFormat(fg: Color(fromHex: "#fb4934")!, bg: Color(fromHex: "#282828")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#8ec07c")!, bg: Color(fromHex: "#282828")!),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#8ec07c")!, bg: Color(fromHex: "#282828")!),
      .nameTag: TextFormat(fg: Color(fromHex: "#8ec07c")!, bg: Color(fromHex: "#282828")!),
      .nameVariable: TextFormat(fg: Color(fromHex: "#83a598")!, bg: Color(fromHex: "#282828")!),
      .number: TextFormat(fg: Color(fromHex: "#d3869b")!, bg: Color(fromHex: "#282828")!),
      .operator: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#282828")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#fb4934")!, bg: Color(fromHex: "#282828")!),
      .other: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#282828")!),
      .punctuation: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#282828")!),
      .string: TextFormat(fg: Color(fromHex: "#b8bb26")!, bg: Color(fromHex: "#282828")!),
      .stringEscape: TextFormat(fg: Color(fromHex: "#fe8019")!, bg: Color(fromHex: "#282828")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#282828")!)
    ]
  }
}
