// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "gruvbox-light" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct GruvboxLightTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#fbf1c7")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#fbf1c7")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#928374")!, bg: Color(fromHex: "#fbf1c7")!, italic: true),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#3c3836")!, bg: Color(fromHex: "#fbf1c7")!, bold: true, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#fbf1c7")!, bg: Color(fromHex: "#9d0006")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#fbf1c7")!, bg: Color(fromHex: "#9d0006")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#fbf1c7")!, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#9d0006")!, bg: Color(fromHex: "#fbf1c7")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#3c3836")!, bg: Color(fromHex: "#fbf1c7")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#fbf1c7")!, bg: Color(fromHex: "#79740e")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#32302f")!, bg: Color(fromHex: "#fbf1c7")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#7c6f64")!, bg: Color(fromHex: "#fbf1c7")!),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#fbf1c7")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#3c3836")!, bg: Color(fromHex: "#fbf1c7")!, underline: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#9d0006")!, bg: Color(fromHex: "#fbf1c7")!),
      .keyword: TextFormat(fg: Color(fromHex: "#9d0006")!, bg: Color(fromHex: "#fbf1c7")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#b57614")!, bg: Color(fromHex: "#fbf1c7")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#af3a03")!, bg: Color(fromHex: "#fbf1c7")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#427b58")!, bg: Color(fromHex: "#fbf1c7")!),
      .nameConstant: TextFormat(fg: Color(fromHex: "#8f3f71")!, bg: Color(fromHex: "#fbf1c7")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#9d0006")!, bg: Color(fromHex: "#fbf1c7")!),
      .nameException: TextFormat(fg: Color(fromHex: "#9d0006")!, bg: Color(fromHex: "#fbf1c7")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#427b58")!, bg: Color(fromHex: "#fbf1c7")!),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#427b58")!, bg: Color(fromHex: "#fbf1c7")!),
      .nameTag: TextFormat(fg: Color(fromHex: "#427b58")!, bg: Color(fromHex: "#fbf1c7")!),
      .nameVariable: TextFormat(fg: Color(fromHex: "#076678")!, bg: Color(fromHex: "#fbf1c7")!),
      .number: TextFormat(fg: Color(fromHex: "#8f3f71")!, bg: Color(fromHex: "#fbf1c7")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#9d0006")!, bg: Color(fromHex: "#fbf1c7")!),
      .string: TextFormat(fg: Color(fromHex: "#79740e")!, bg: Color(fromHex: "#fbf1c7")!),
      .stringEscape: TextFormat(fg: Color(fromHex: "#af3a03")!, bg: Color(fromHex: "#fbf1c7")!)
    ]
  }
}
