// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "igor" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct IgorTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#ffffff")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .keyword: TextFormat(fg: Color(fromHex: "#00f")!, bg: Color(fromHex: "#ffffff")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#007575")!, bg: Color(fromHex: "#ffffff")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#cc00a3")!, bg: Color(fromHex: "#ffffff")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#c34e00")!, bg: Color(fromHex: "#ffffff")!),
      .string: TextFormat(fg: Color(fromHex: "#009c00")!, bg: Color(fromHex: "#ffffff")!)
    ]
  }
}
