// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "igor" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct IgorTheme: CodeTheme {
  public init() {}

  private static let hex000000: UInt32 = 0x000000ff
  private static let hex007575: UInt32 = 0x007575ff
  private static let hex009c00: UInt32 = 0x009c00ff
  private static let hex00f: UInt32 = 0x00fff
  private static let hexc34e00: UInt32 = 0xc34e00ff
  private static let hexcc00a3: UInt32 = 0xcc00a3ff
  private static let hexf00: UInt32 = 0xf00ff
  private static let hexffffff: UInt32 = 0xffffffff

  public func getBgColor() -> Color { Color(rgba: Self.hexffffff) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hexf00), bg: Color(rgba: Self.hexffffff), italic: true),
      .keyword: TextFormat(fg: Color(rgba: Self.hex00f), bg: Color(rgba: Self.hexffffff)),
      .nameClass: TextFormat(fg: Color(rgba: Self.hex007575), bg: Color(rgba: Self.hexffffff)),
      .nameDecorator: TextFormat(fg: Color(rgba: Self.hexcc00a3), bg: Color(rgba: Self.hexffffff)),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hexc34e00), bg: Color(rgba: Self.hexffffff)),
      .string: TextFormat(fg: Color(rgba: Self.hex009c00), bg: Color(rgba: Self.hexffffff)),
    ]
  }
}
