// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "inkpot" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct InkpotTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#1e1e27")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#1e1e27")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#cd8b00")!, bg: Color(fromHex: "#1e1e27")!),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#409090")!, bg: Color(fromHex: "#1e1e27")!),
      .commentPreprocFile: TextFormat(fg: Color(fromHex: "#ffcd8b")!, bg: Color(fromHex: "#404040")!),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#808bed")!, bg: Color(fromHex: "#1e1e27")!),
      .error: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#6e2e2e")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#a00000")!, bg: Color(fromHex: "#1e1e27")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#1e1e27")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#1e1e27")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#1e1e27")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#1e1e27")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#00a000")!, bg: Color(fromHex: "#1e1e27")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#1e1e27")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#1e1e27")!, bold: true),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#1e1e27")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#800080")!, bg: Color(fromHex: "#1e1e27")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#04d")!, bg: Color(fromHex: "#1e1e27")!),
      .keyword: TextFormat(fg: Color(fromHex: "#808bed")!, bg: Color(fromHex: "#1e1e27")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#ff8bff")!, bg: Color(fromHex: "#1e1e27")!),
      .name: TextFormat(fg: Color(fromHex: "#cfbfad")!, bg: Color(fromHex: "#1e1e27")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#808bed")!, bg: Color(fromHex: "#1e1e27")!),
      .nameBuiltinPseudo: TextFormat(fg: Color(fromHex: "#ff0")!, bg: Color(fromHex: "#1e1e27")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#ff8bff")!, bg: Color(fromHex: "#1e1e27")!),
      .nameConstant: TextFormat(fg: Color(fromHex: "#409090")!, bg: Color(fromHex: "#1e1e27")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#409090")!, bg: Color(fromHex: "#1e1e27")!),
      .nameException: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#1e1e27")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#c080d0")!, bg: Color(fromHex: "#1e1e27")!),
      .nameLabel: TextFormat(fg: Color(fromHex: "#808bed")!, bg: Color(fromHex: "#1e1e27")!),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#1e1e27")!),
      .number: TextFormat(fg: Color(fromHex: "#f0ad6d")!, bg: Color(fromHex: "#1e1e27")!),
      .operator: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#1e1e27")!),
      .other: TextFormat(fg: Color(fromHex: "#cfbfad")!, bg: Color(fromHex: "#1e1e27")!),
      .punctuation: TextFormat(fg: Color(fromHex: "#cfbfad")!, bg: Color(fromHex: "#1e1e27")!),
      .string: TextFormat(fg: Color(fromHex: "#ffcd8b")!, bg: Color(fromHex: "#404040")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#808bed")!, bg: Color(fromHex: "#404040")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#434357")!, bg: Color(fromHex: "#1e1e27")!)
    ]
  }
}
