// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "lightbulb" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct LightbulbTheme: CodeTheme {
  public init() {}

  private static let hex19362c: UInt32 = 0x19362cff
  private static let hex1d2331: UInt32 = 0x1d2331ff
  private static let hex3d1e20: UInt32 = 0x3d1e20ff
  private static let hex5ccfe6: UInt32 = 0x5ccfe6ff
  private static let hex6ad4af: UInt32 = 0x6ad4afff
  private static let hex73d0ff: UInt32 = 0x73d0ffff
  private static let hex7e8aa1: UInt32 = 0x7e8aa1ff
  private static let hex95e6cb: UInt32 = 0x95e6cbff
  private static let hexd4d2c8: UInt32 = 0xd4d2c8ff
  private static let hexd5ff80: UInt32 = 0xd5ff80ff
  private static let hexdfbfff: UInt32 = 0xdfbfffff
  private static let hexf29e74: UInt32 = 0xf29e74ff
  private static let hexf88f7f: UInt32 = 0xf88f7fff
  private static let hexffad66: UInt32 = 0xffad66ff
  private static let hexffd173: UInt32 = 0xffd173ff

  public func getBgColor() -> Color { Color(rgba: Self.hex1d2331) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hexd4d2c8), bg: Color(rgba: Self.hex1d2331)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hex7e8aa1), bg: Color(rgba: Self.hex1d2331)),
      .commentHashbang: TextFormat(fg: Color(rgba: Self.hexf88f7f), bg: Color(rgba: Self.hex1d2331), italic: true),
      .commentPreproc: TextFormat(fg: Color(rgba: Self.hexffad66), bg: Color(rgba: Self.hex1d2331), bold: true),
      .commentSpecial: TextFormat(fg: Color(rgba: Self.hex7e8aa1), bg: Color(rgba: Self.hex1d2331), italic: true),
      .error: TextFormat(fg: Color(rgba: Self.hexf88f7f), bg: Color(rgba: Self.hex1d2331)),
      .genericDeleted: TextFormat(fg: Color(rgba: Self.hexf88f7f), bg: Color(rgba: Self.hex3d1e20)),
      .genericEmph: TextFormat(fg: Color(rgba: Self.hexd4d2c8), bg: Color(rgba: Self.hex1d2331), italic: true),
      .genericError: TextFormat(fg: Color(rgba: Self.hexf88f7f), bg: Color(rgba: Self.hex1d2331)),
      .genericInserted: TextFormat(fg: Color(rgba: Self.hex6ad4af), bg: Color(rgba: Self.hex19362c)),
      .genericOutput: TextFormat(fg: Color(rgba: Self.hex7e8aa1), bg: Color(rgba: Self.hex1d2331)),
      .genericStrong: TextFormat(fg: Color(rgba: Self.hexd4d2c8), bg: Color(rgba: Self.hex1d2331), bold: true),
      .genericTraceback: TextFormat(fg: Color(rgba: Self.hexf88f7f), bg: Color(rgba: Self.hex1d2331)),
      .keyword: TextFormat(fg: Color(rgba: Self.hexffad66), bg: Color(rgba: Self.hex1d2331)),
      .keywordType: TextFormat(fg: Color(rgba: Self.hex73d0ff), bg: Color(rgba: Self.hex1d2331)),
      .literal: TextFormat(fg: Color(rgba: Self.hexd5ff80), bg: Color(rgba: Self.hex1d2331)),
      .nameAttribute: TextFormat(fg: Color(rgba: Self.hexffd173), bg: Color(rgba: Self.hex1d2331)),
      .nameBuiltin: TextFormat(fg: Color(rgba: Self.hexffd173), bg: Color(rgba: Self.hex1d2331)),
      .nameBuiltinPseudo: TextFormat(fg: Color(rgba: Self.hex5ccfe6), bg: Color(rgba: Self.hex1d2331)),
      .nameClass: TextFormat(fg: Color(rgba: Self.hex73d0ff), bg: Color(rgba: Self.hex1d2331)),
      .nameConstant: TextFormat(fg: Color(rgba: Self.hexffd173), bg: Color(rgba: Self.hex1d2331)),
      .nameDecorator: TextFormat(fg: Color(rgba: Self.hex7e8aa1), bg: Color(rgba: Self.hex1d2331), bold: true, italic: true),
      .nameEntity: TextFormat(fg: Color(rgba: Self.hex95e6cb), bg: Color(rgba: Self.hex1d2331)),
      .nameException: TextFormat(fg: Color(rgba: Self.hex73d0ff), bg: Color(rgba: Self.hex1d2331)),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hexffd173), bg: Color(rgba: Self.hex1d2331)),
      .nameProperty: TextFormat(fg: Color(rgba: Self.hexffd173), bg: Color(rgba: Self.hex1d2331)),
      .nameTag: TextFormat(fg: Color(rgba: Self.hex5ccfe6), bg: Color(rgba: Self.hex1d2331)),
      .number: TextFormat(fg: Color(rgba: Self.hexdfbfff), bg: Color(rgba: Self.hex1d2331)),
      .operator: TextFormat(fg: Color(rgba: Self.hexffad66), bg: Color(rgba: Self.hex1d2331)),
      .stringAffix: TextFormat(fg: Color(rgba: Self.hexf29e74), bg: Color(rgba: Self.hex1d2331)),
      .stringDoc: TextFormat(fg: Color(rgba: Self.hex7e8aa1), bg: Color(rgba: Self.hex1d2331)),
      .stringEscape: TextFormat(fg: Color(rgba: Self.hex95e6cb), bg: Color(rgba: Self.hex1d2331)),
      .stringInterpol: TextFormat(fg: Color(rgba: Self.hex95e6cb), bg: Color(rgba: Self.hex1d2331)),
      .stringOther: TextFormat(fg: Color(rgba: Self.hex95e6cb), bg: Color(rgba: Self.hex1d2331)),
      .stringRegex: TextFormat(fg: Color(rgba: Self.hex95e6cb), bg: Color(rgba: Self.hex1d2331)),
      .stringSymbol: TextFormat(fg: Color(rgba: Self.hexdfbfff), bg: Color(rgba: Self.hex1d2331)),
    ]
  }
}
