// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "lightbulb" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct LightbulbTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#1d2331")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#d4d2c8")!, bg: Color(fromHex: "#1d2331")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#7e8aa1")!, bg: Color(fromHex: "#1d2331")!),
      .commentHashbang: TextFormat(fg: Color(fromHex: "#f88f7f")!, bg: Color(fromHex: "#1d2331")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#ffad66")!, bg: Color(fromHex: "#1d2331")!, bold: true),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#7e8aa1")!, bg: Color(fromHex: "#1d2331")!, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#f88f7f")!, bg: Color(fromHex: "#1d2331")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#f88f7f")!, bg: Color(fromHex: "#3d1e20")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#d4d2c8")!, bg: Color(fromHex: "#1d2331")!, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#f88f7f")!, bg: Color(fromHex: "#1d2331")!),
      .genericInserted: TextFormat(fg: Color(fromHex: "#6ad4af")!, bg: Color(fromHex: "#19362c")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#7e8aa1")!, bg: Color(fromHex: "#1d2331")!),
      .genericStrong: TextFormat(fg: Color(fromHex: "#d4d2c8")!, bg: Color(fromHex: "#1d2331")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#f88f7f")!, bg: Color(fromHex: "#1d2331")!),
      .keyword: TextFormat(fg: Color(fromHex: "#ffad66")!, bg: Color(fromHex: "#1d2331")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#73d0ff")!, bg: Color(fromHex: "#1d2331")!),
      .literal: TextFormat(fg: Color(fromHex: "#d5ff80")!, bg: Color(fromHex: "#1d2331")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#ffd173")!, bg: Color(fromHex: "#1d2331")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#ffd173")!, bg: Color(fromHex: "#1d2331")!),
      .nameBuiltinPseudo: TextFormat(fg: Color(fromHex: "#5ccfe6")!, bg: Color(fromHex: "#1d2331")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#73d0ff")!, bg: Color(fromHex: "#1d2331")!),
      .nameConstant: TextFormat(fg: Color(fromHex: "#ffd173")!, bg: Color(fromHex: "#1d2331")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#7e8aa1")!, bg: Color(fromHex: "#1d2331")!, bold: true, italic: true),
      .nameEntity: TextFormat(fg: Color(fromHex: "#95e6cb")!, bg: Color(fromHex: "#1d2331")!),
      .nameException: TextFormat(fg: Color(fromHex: "#73d0ff")!, bg: Color(fromHex: "#1d2331")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#ffd173")!, bg: Color(fromHex: "#1d2331")!),
      .nameProperty: TextFormat(fg: Color(fromHex: "#ffd173")!, bg: Color(fromHex: "#1d2331")!),
      .nameTag: TextFormat(fg: Color(fromHex: "#5ccfe6")!, bg: Color(fromHex: "#1d2331")!),
      .number: TextFormat(fg: Color(fromHex: "#dfbfff")!, bg: Color(fromHex: "#1d2331")!),
      .operator: TextFormat(fg: Color(fromHex: "#ffad66")!, bg: Color(fromHex: "#1d2331")!),
      .stringAffix: TextFormat(fg: Color(fromHex: "#f29e74")!, bg: Color(fromHex: "#1d2331")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#7e8aa1")!, bg: Color(fromHex: "#1d2331")!),
      .stringEscape: TextFormat(fg: Color(fromHex: "#95e6cb")!, bg: Color(fromHex: "#1d2331")!),
      .stringInterpol: TextFormat(fg: Color(fromHex: "#95e6cb")!, bg: Color(fromHex: "#1d2331")!),
      .stringOther: TextFormat(fg: Color(fromHex: "#95e6cb")!, bg: Color(fromHex: "#1d2331")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#95e6cb")!, bg: Color(fromHex: "#1d2331")!),
      .stringSymbol: TextFormat(fg: Color(fromHex: "#dfbfff")!, bg: Color(fromHex: "#1d2331")!)
    ]
  }
}
