// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "lilypond" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct LilypondTheme: CodeTheme {
  public init() {}

  private static let hex000000: UInt32 = 0x000000ff
  private static let hex976806: UInt32 = 0x976806ff
  private static let hexa3aab2: UInt32 = 0xa3aab2ff
  private static let hexab0909: UInt32 = 0xab0909ff
  private static let hexc46c6c: UInt32 = 0xc46c6cff
  private static let hexffffff: UInt32 = 0xffffffff

  public func getBgColor() -> Color { Color(rgba: Self.hexffffff) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hexa3aab2), bg: Color(rgba: Self.hexffffff), italic: true),
      .keyword: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true),
      .number: TextFormat(fg: Color(rgba: Self.hex976806), bg: Color(rgba: Self.hexffffff)),
      .string: TextFormat(fg: Color(rgba: Self.hexab0909), bg: Color(rgba: Self.hexffffff)),
      .stringEscape: TextFormat(fg: Color(rgba: Self.hexc46c6c), bg: Color(rgba: Self.hexffffff)),
    ]
  }
}
