// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "lilypond" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct LilypondTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#ffffff")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#a3aab2")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .keyword: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .number: TextFormat(fg: Color(fromHex: "#976806")!, bg: Color(fromHex: "#ffffff")!),
      .string: TextFormat(fg: Color(fromHex: "#ab0909")!, bg: Color(fromHex: "#ffffff")!),
      .stringEscape: TextFormat(fg: Color(fromHex: "#c46c6c")!, bg: Color(fromHex: "#ffffff")!),
    ]
  }
}
