// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "lovelace" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct LovelaceTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#ffffff")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .commentHashbang: TextFormat(fg: Color(fromHex: "#287088")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#289870")!, bg: Color(fromHex: "#ffffff")!),
      .error: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#a848a8")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#c02828")!, bg: Color(fromHex: "#ffffff")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#c02828")!, bg: Color(fromHex: "#ffffff")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#ffffff")!),
      .genericInserted: TextFormat(fg: Color(fromHex: "#388038")!, bg: Color(fromHex: "#ffffff")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#ffffff")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#444")!, bg: Color(fromHex: "#ffffff")!),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#444")!, bg: Color(fromHex: "#ffffff")!),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#2838b0")!, bg: Color(fromHex: "#ffffff")!),
      .keyword: TextFormat(fg: Color(fromHex: "#2838b0")!, bg: Color(fromHex: "#ffffff")!),
      .keywordConstant: TextFormat(fg: Color(fromHex: "#444")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .keywordDeclaration: TextFormat(fg: Color(fromHex: "#2838b0")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .keywordType: TextFormat(fg: Color(fromHex: "#2838b0")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#388038")!, bg: Color(fromHex: "#ffffff")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#388038")!, bg: Color(fromHex: "#ffffff")!),
      .nameBuiltinPseudo: TextFormat(fg: Color(fromHex: "#388038")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .nameClass: TextFormat(fg: Color(fromHex: "#287088")!, bg: Color(fromHex: "#ffffff")!),
      .nameConstant: TextFormat(fg: Color(fromHex: "#b85820")!, bg: Color(fromHex: "#ffffff")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#287088")!, bg: Color(fromHex: "#ffffff")!),
      .nameEntity: TextFormat(fg: Color(fromHex: "#709030")!, bg: Color(fromHex: "#ffffff")!),
      .nameException: TextFormat(fg: Color(fromHex: "#908828")!, bg: Color(fromHex: "#ffffff")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#785840")!, bg: Color(fromHex: "#ffffff")!),
      .nameFunctionMagic: TextFormat(fg: Color(fromHex: "#b85820")!, bg: Color(fromHex: "#ffffff")!),
      .nameLabel: TextFormat(fg: Color(fromHex: "#289870")!, bg: Color(fromHex: "#ffffff")!),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#289870")!, bg: Color(fromHex: "#ffffff")!),
      .nameTag: TextFormat(fg: Color(fromHex: "#2838b0")!, bg: Color(fromHex: "#ffffff")!),
      .nameVariable: TextFormat(fg: Color(fromHex: "#b04040")!, bg: Color(fromHex: "#ffffff")!),
      .nameVariableGlobal: TextFormat(fg: Color(fromHex: "#908828")!, bg: Color(fromHex: "#ffffff")!),
      .nameVariableMagic: TextFormat(fg: Color(fromHex: "#b85820")!, bg: Color(fromHex: "#ffffff")!),
      .number: TextFormat(fg: Color(fromHex: "#444")!, bg: Color(fromHex: "#ffffff")!),
      .operator: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#ffffff")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#a848a8")!, bg: Color(fromHex: "#ffffff")!),
      .punctuation: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#ffffff")!),
      .string: TextFormat(fg: Color(fromHex: "#b83838")!, bg: Color(fromHex: "#ffffff")!),
      .stringAffix: TextFormat(fg: Color(fromHex: "#444")!, bg: Color(fromHex: "#ffffff")!),
      .stringChar: TextFormat(fg: Color(fromHex: "#a848a8")!, bg: Color(fromHex: "#ffffff")!),
      .stringDelimiter: TextFormat(fg: Color(fromHex: "#b85820")!, bg: Color(fromHex: "#ffffff")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#b85820")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .stringEscape: TextFormat(fg: Color(fromHex: "#709030")!, bg: Color(fromHex: "#ffffff")!),
      .stringInterpol: TextFormat(fg: Color(fromHex: "#b83838")!, bg: Color(fromHex: "#ffffff")!, underline: true),
      .stringOther: TextFormat(fg: Color(fromHex: "#a848a8")!, bg: Color(fromHex: "#ffffff")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#a848a8")!, bg: Color(fromHex: "#ffffff")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#a89028")!, bg: Color(fromHex: "#ffffff")!),
    ]
  }
}
