// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "lovelace" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct LovelaceTheme: CodeTheme {
  public init() {}

  private static let hex000000: UInt32 = 0x000000ff
  private static let hex2838b0: UInt32 = 0x2838b0ff
  private static let hex287088: UInt32 = 0x287088ff
  private static let hex289870: UInt32 = 0x289870ff
  private static let hex388038: UInt32 = 0x388038ff
  private static let hex444: UInt32 = 0x444ff
  private static let hex666: UInt32 = 0x666ff
  private static let hex709030: UInt32 = 0x709030ff
  private static let hex785840: UInt32 = 0x785840ff
  private static let hex888: UInt32 = 0x888ff
  private static let hex908828: UInt32 = 0x908828ff
  private static let hexa848a8: UInt32 = 0xa848a8ff
  private static let hexa89028: UInt32 = 0xa89028ff
  private static let hexb04040: UInt32 = 0xb04040ff
  private static let hexb83838: UInt32 = 0xb83838ff
  private static let hexb85820: UInt32 = 0xb85820ff
  private static let hexc02828: UInt32 = 0xc02828ff
  private static let hexffffff: UInt32 = 0xffffffff

  public func getBgColor() -> Color { Color(rgba: Self.hexffffff) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hex888), bg: Color(rgba: Self.hexffffff), italic: true),
      .commentHashbang: TextFormat(fg: Color(rgba: Self.hex287088), bg: Color(rgba: Self.hexffffff), italic: true),
      .commentPreproc: TextFormat(fg: Color(rgba: Self.hex289870), bg: Color(rgba: Self.hexffffff)),
      .error: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexa848a8)),
      .genericDeleted: TextFormat(fg: Color(rgba: Self.hexc02828), bg: Color(rgba: Self.hexffffff)),
      .genericEmph: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), italic: true),
      .genericEmphStrong: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true, italic: true),
      .genericError: TextFormat(fg: Color(rgba: Self.hexc02828), bg: Color(rgba: Self.hexffffff)),
      .genericHeading: TextFormat(fg: Color(rgba: Self.hex666), bg: Color(rgba: Self.hexffffff)),
      .genericInserted: TextFormat(fg: Color(rgba: Self.hex388038), bg: Color(rgba: Self.hexffffff)),
      .genericOutput: TextFormat(fg: Color(rgba: Self.hex666), bg: Color(rgba: Self.hexffffff)),
      .genericPrompt: TextFormat(fg: Color(rgba: Self.hex444), bg: Color(rgba: Self.hexffffff)),
      .genericStrong: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true),
      .genericSubheading: TextFormat(fg: Color(rgba: Self.hex444), bg: Color(rgba: Self.hexffffff)),
      .genericTraceback: TextFormat(fg: Color(rgba: Self.hex2838b0), bg: Color(rgba: Self.hexffffff)),
      .keyword: TextFormat(fg: Color(rgba: Self.hex2838b0), bg: Color(rgba: Self.hexffffff)),
      .keywordConstant: TextFormat(fg: Color(rgba: Self.hex444), bg: Color(rgba: Self.hexffffff), italic: true),
      .keywordDeclaration: TextFormat(fg: Color(rgba: Self.hex2838b0), bg: Color(rgba: Self.hexffffff), italic: true),
      .keywordType: TextFormat(fg: Color(rgba: Self.hex2838b0), bg: Color(rgba: Self.hexffffff), italic: true),
      .nameAttribute: TextFormat(fg: Color(rgba: Self.hex388038), bg: Color(rgba: Self.hexffffff)),
      .nameBuiltin: TextFormat(fg: Color(rgba: Self.hex388038), bg: Color(rgba: Self.hexffffff)),
      .nameBuiltinPseudo: TextFormat(fg: Color(rgba: Self.hex388038), bg: Color(rgba: Self.hexffffff), italic: true),
      .nameClass: TextFormat(fg: Color(rgba: Self.hex287088), bg: Color(rgba: Self.hexffffff)),
      .nameConstant: TextFormat(fg: Color(rgba: Self.hexb85820), bg: Color(rgba: Self.hexffffff)),
      .nameDecorator: TextFormat(fg: Color(rgba: Self.hex287088), bg: Color(rgba: Self.hexffffff)),
      .nameEntity: TextFormat(fg: Color(rgba: Self.hex709030), bg: Color(rgba: Self.hexffffff)),
      .nameException: TextFormat(fg: Color(rgba: Self.hex908828), bg: Color(rgba: Self.hexffffff)),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hex785840), bg: Color(rgba: Self.hexffffff)),
      .nameFunctionMagic: TextFormat(fg: Color(rgba: Self.hexb85820), bg: Color(rgba: Self.hexffffff)),
      .nameLabel: TextFormat(fg: Color(rgba: Self.hex289870), bg: Color(rgba: Self.hexffffff)),
      .nameNamespace: TextFormat(fg: Color(rgba: Self.hex289870), bg: Color(rgba: Self.hexffffff)),
      .nameTag: TextFormat(fg: Color(rgba: Self.hex2838b0), bg: Color(rgba: Self.hexffffff)),
      .nameVariable: TextFormat(fg: Color(rgba: Self.hexb04040), bg: Color(rgba: Self.hexffffff)),
      .nameVariableGlobal: TextFormat(fg: Color(rgba: Self.hex908828), bg: Color(rgba: Self.hexffffff)),
      .nameVariableMagic: TextFormat(fg: Color(rgba: Self.hexb85820), bg: Color(rgba: Self.hexffffff)),
      .number: TextFormat(fg: Color(rgba: Self.hex444), bg: Color(rgba: Self.hexffffff)),
      .operator: TextFormat(fg: Color(rgba: Self.hex666), bg: Color(rgba: Self.hexffffff)),
      .operatorWord: TextFormat(fg: Color(rgba: Self.hexa848a8), bg: Color(rgba: Self.hexffffff)),
      .punctuation: TextFormat(fg: Color(rgba: Self.hex888), bg: Color(rgba: Self.hexffffff)),
      .string: TextFormat(fg: Color(rgba: Self.hexb83838), bg: Color(rgba: Self.hexffffff)),
      .stringAffix: TextFormat(fg: Color(rgba: Self.hex444), bg: Color(rgba: Self.hexffffff)),
      .stringChar: TextFormat(fg: Color(rgba: Self.hexa848a8), bg: Color(rgba: Self.hexffffff)),
      .stringDelimiter: TextFormat(fg: Color(rgba: Self.hexb85820), bg: Color(rgba: Self.hexffffff)),
      .stringDoc: TextFormat(fg: Color(rgba: Self.hexb85820), bg: Color(rgba: Self.hexffffff), italic: true),
      .stringEscape: TextFormat(fg: Color(rgba: Self.hex709030), bg: Color(rgba: Self.hexffffff)),
      .stringInterpol: TextFormat(fg: Color(rgba: Self.hexb83838), bg: Color(rgba: Self.hexffffff), underline: true),
      .stringOther: TextFormat(fg: Color(rgba: Self.hexa848a8), bg: Color(rgba: Self.hexffffff)),
      .stringRegex: TextFormat(fg: Color(rgba: Self.hexa848a8), bg: Color(rgba: Self.hexffffff)),
      .whitespace: TextFormat(fg: Color(rgba: Self.hexa89028), bg: Color(rgba: Self.hexffffff)),
    ]
  }
}
