// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "manni" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct ManniTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#f0f3f3")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f0f3f3")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#09f")!, bg: Color(fromHex: "#f0f3f3")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#099")!, bg: Color(fromHex: "#f0f3f3")!),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#09f")!, bg: Color(fromHex: "#f0f3f3")!, bold: true, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#a00")!, bg: Color(fromHex: "#faa")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#fcc")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f0f3f3")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f0f3f3")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#f0f3f3")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#030")!, bg: Color(fromHex: "#f0f3f3")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#cfc")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#aaa")!, bg: Color(fromHex: "#f0f3f3")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#009")!, bg: Color(fromHex: "#f0f3f3")!, bold: true),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f0f3f3")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#030")!, bg: Color(fromHex: "#f0f3f3")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#9c6")!, bg: Color(fromHex: "#f0f3f3")!),
      .keyword: TextFormat(fg: Color(fromHex: "#069")!, bg: Color(fromHex: "#f0f3f3")!, bold: true),
      .keywordPseudo: TextFormat(fg: Color(fromHex: "#069")!, bg: Color(fromHex: "#f0f3f3")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#078")!, bg: Color(fromHex: "#f0f3f3")!, bold: true),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#309")!, bg: Color(fromHex: "#f0f3f3")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#366")!, bg: Color(fromHex: "#f0f3f3")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#0a8")!, bg: Color(fromHex: "#f0f3f3")!, bold: true),
      .nameConstant: TextFormat(fg: Color(fromHex: "#360")!, bg: Color(fromHex: "#f0f3f3")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#99f")!, bg: Color(fromHex: "#f0f3f3")!),
      .nameEntity: TextFormat(fg: Color(fromHex: "#999")!, bg: Color(fromHex: "#f0f3f3")!, bold: true),
      .nameException: TextFormat(fg: Color(fromHex: "#c00")!, bg: Color(fromHex: "#f0f3f3")!, bold: true),
      .nameFunction: TextFormat(fg: Color(fromHex: "#c0f")!, bg: Color(fromHex: "#f0f3f3")!),
      .nameLabel: TextFormat(fg: Color(fromHex: "#99f")!, bg: Color(fromHex: "#f0f3f3")!),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#0cf")!, bg: Color(fromHex: "#f0f3f3")!, bold: true),
      .nameTag: TextFormat(fg: Color(fromHex: "#309")!, bg: Color(fromHex: "#f0f3f3")!, bold: true),
      .nameVariable: TextFormat(fg: Color(fromHex: "#033")!, bg: Color(fromHex: "#f0f3f3")!),
      .number: TextFormat(fg: Color(fromHex: "#f60")!, bg: Color(fromHex: "#f0f3f3")!),
      .operator: TextFormat(fg: Color(fromHex: "#555")!, bg: Color(fromHex: "#f0f3f3")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#f0f3f3")!, bold: true),
      .string: TextFormat(fg: Color(fromHex: "#c30")!, bg: Color(fromHex: "#f0f3f3")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#c30")!, bg: Color(fromHex: "#f0f3f3")!, italic: true),
      .stringEscape: TextFormat(fg: Color(fromHex: "#c30")!, bg: Color(fromHex: "#f0f3f3")!, bold: true),
      .stringInterpol: TextFormat(fg: Color(fromHex: "#a00")!, bg: Color(fromHex: "#f0f3f3")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#3aa")!, bg: Color(fromHex: "#f0f3f3")!),
      .stringSymbol: TextFormat(fg: Color(fromHex: "#fc3")!, bg: Color(fromHex: "#f0f3f3")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#bbb")!, bg: Color(fromHex: "#f0f3f3")!)
    ]
  }
}
