// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "material" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct MaterialTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#263238")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#263238")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#546e7a")!, bg: Color(fromHex: "#263238")!, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#ff5370")!, bg: Color(fromHex: "#263238")!),
      .escape: TextFormat(fg: Color(fromHex: "#89ddff")!, bg: Color(fromHex: "#263238")!),
      .generic: TextFormat(fg: Color(fromHex: "#eff")!, bg: Color(fromHex: "#263238")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#ff5370")!, bg: Color(fromHex: "#263238")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#89ddff")!, bg: Color(fromHex: "#263238")!),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#ffcb6b")!, bg: Color(fromHex: "#263238")!),
      .genericError: TextFormat(fg: Color(fromHex: "#ff5370")!, bg: Color(fromHex: "#263238")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#c3e88d")!, bg: Color(fromHex: "#263238")!),
      .genericInserted: TextFormat(fg: Color(fromHex: "#c3e88d")!, bg: Color(fromHex: "#263238")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#546e7a")!, bg: Color(fromHex: "#263238")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#ffcb6b")!, bg: Color(fromHex: "#263238")!),
      .genericStrong: TextFormat(fg: Color(fromHex: "#ff5370")!, bg: Color(fromHex: "#263238")!),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#89ddff")!, bg: Color(fromHex: "#263238")!),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#ff5370")!, bg: Color(fromHex: "#263238")!),
      .keyword: TextFormat(fg: Color(fromHex: "#bb80b3")!, bg: Color(fromHex: "#263238")!),
      .keywordConstant: TextFormat(fg: Color(fromHex: "#89ddff")!, bg: Color(fromHex: "#263238")!),
      .keywordNamespace: TextFormat(fg: Color(fromHex: "#89ddff")!, bg: Color(fromHex: "#263238")!, italic: true),
      .keywordPseudo: TextFormat(fg: Color(fromHex: "#89ddff")!, bg: Color(fromHex: "#263238")!),
      .literal: TextFormat(fg: Color(fromHex: "#c3e88d")!, bg: Color(fromHex: "#263238")!),
      .name: TextFormat(fg: Color(fromHex: "#eff")!, bg: Color(fromHex: "#263238")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#bb80b3")!, bg: Color(fromHex: "#263238")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#82aaff")!, bg: Color(fromHex: "#263238")!),
      .nameBuiltinPseudo: TextFormat(fg: Color(fromHex: "#89ddff")!, bg: Color(fromHex: "#263238")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#ffcb6b")!, bg: Color(fromHex: "#263238")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#82aaff")!, bg: Color(fromHex: "#263238")!),
      .nameEntity: TextFormat(fg: Color(fromHex: "#89ddff")!, bg: Color(fromHex: "#263238")!),
      .nameException: TextFormat(fg: Color(fromHex: "#ffcb6b")!, bg: Color(fromHex: "#263238")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#82aaff")!, bg: Color(fromHex: "#263238")!),
      .nameLabel: TextFormat(fg: Color(fromHex: "#82aaff")!, bg: Color(fromHex: "#263238")!),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#ffcb6b")!, bg: Color(fromHex: "#263238")!),
      .nameProperty: TextFormat(fg: Color(fromHex: "#ffcb6b")!, bg: Color(fromHex: "#263238")!),
      .nameTag: TextFormat(fg: Color(fromHex: "#ff5370")!, bg: Color(fromHex: "#263238")!),
      .nameVariable: TextFormat(fg: Color(fromHex: "#89ddff")!, bg: Color(fromHex: "#263238")!),
      .nameVariableMagic: TextFormat(fg: Color(fromHex: "#82aaff")!, bg: Color(fromHex: "#263238")!),
      .number: TextFormat(fg: Color(fromHex: "#f78c6c")!, bg: Color(fromHex: "#263238")!),
      .operator: TextFormat(fg: Color(fromHex: "#89ddff")!, bg: Color(fromHex: "#263238")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#89ddff")!, bg: Color(fromHex: "#263238")!, italic: true),
      .punctuation: TextFormat(fg: Color(fromHex: "#89ddff")!, bg: Color(fromHex: "#263238")!),
      .stringAffix: TextFormat(fg: Color(fromHex: "#bb80b3")!, bg: Color(fromHex: "#263238")!),
      .stringDelimiter: TextFormat(fg: Color(fromHex: "#eff")!, bg: Color(fromHex: "#263238")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#546e7a")!, bg: Color(fromHex: "#263238")!, italic: true),
      .stringEscape: TextFormat(fg: Color(fromHex: "#eff")!, bg: Color(fromHex: "#263238")!),
      .stringInterpol: TextFormat(fg: Color(fromHex: "#89ddff")!, bg: Color(fromHex: "#263238")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#89ddff")!, bg: Color(fromHex: "#263238")!),
      .stringSymbol: TextFormat(fg: Color(fromHex: "#89ddff")!, bg: Color(fromHex: "#263238")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#eff")!, bg: Color(fromHex: "#263238")!)
    ]
  }
}
