// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "monokai" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct MonokaiTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#272822")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#272822")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#959077")!, bg: Color(fromHex: "#272822")!),
      .error: TextFormat(fg: Color(fromHex: "#ed007e")!, bg: Color(fromHex: "#1e0010")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#ff4689")!, bg: Color(fromHex: "#272822")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#272822")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#272822")!, bold: true, italic: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#a6e22e")!, bg: Color(fromHex: "#272822")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#66d9ef")!, bg: Color(fromHex: "#272822")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#ff4689")!, bg: Color(fromHex: "#272822")!, bold: true),
      .genericStrong: TextFormat(fg: Color(fromHex: "#f8f8f2")!, bg: Color(fromHex: "#272822")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#959077")!, bg: Color(fromHex: "#272822")!),
      .keyword: TextFormat(fg: Color(fromHex: "#66d9ef")!, bg: Color(fromHex: "#272822")!),
      .keywordNamespace: TextFormat(fg: Color(fromHex: "#ff4689")!, bg: Color(fromHex: "#272822")!),
      .literal: TextFormat(fg: Color(fromHex: "#ae81ff")!, bg: Color(fromHex: "#272822")!),
      .literalDate: TextFormat(fg: Color(fromHex: "#e6db74")!, bg: Color(fromHex: "#272822")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#a6e22e")!, bg: Color(fromHex: "#272822")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#a6e22e")!, bg: Color(fromHex: "#272822")!),
      .nameConstant: TextFormat(fg: Color(fromHex: "#66d9ef")!, bg: Color(fromHex: "#272822")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#a6e22e")!, bg: Color(fromHex: "#272822")!),
      .nameException: TextFormat(fg: Color(fromHex: "#a6e22e")!, bg: Color(fromHex: "#272822")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#a6e22e")!, bg: Color(fromHex: "#272822")!),
      .nameOther: TextFormat(fg: Color(fromHex: "#a6e22e")!, bg: Color(fromHex: "#272822")!),
      .nameTag: TextFormat(fg: Color(fromHex: "#ff4689")!, bg: Color(fromHex: "#272822")!),
      .operator: TextFormat(fg: Color(fromHex: "#ff4689")!, bg: Color(fromHex: "#272822")!),
      .string: TextFormat(fg: Color(fromHex: "#e6db74")!, bg: Color(fromHex: "#272822")!),
      .stringEscape: TextFormat(fg: Color(fromHex: "#ae81ff")!, bg: Color(fromHex: "#272822")!),
    ]
  }
}
