// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "native" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct NativeTheme: CodeTheme {
  public init() {}

  private static let hex202020: UInt32 = 0x202020ff
  private static let hex2fbccd: UInt32 = 0x2fbccdff
  private static let hex40ffff: UInt32 = 0x40ffffff
  private static let hex51b2fd: UInt32 = 0x51b2fdff
  private static let hex520000: UInt32 = 0x520000ff
  private static let hex589819: UInt32 = 0x589819ff
  private static let hex666: UInt32 = 0x666ff
  private static let hex6ebf26: UInt32 = 0x6ebf26ff
  private static let hex71adff: UInt32 = 0x71adffff
  private static let hexa61717: UInt32 = 0xa61717ff
  private static let hexaaa: UInt32 = 0xaaaff
  private static let hexababab: UInt32 = 0xabababff
  private static let hexbbb: UInt32 = 0xbbbff
  private static let hexccc: UInt32 = 0xcccff
  private static let hexd0d0d0: UInt32 = 0xd0d0d0ff
  private static let hexe3d2d2: UInt32 = 0xe3d2d2ff
  private static let hexe50808: UInt32 = 0xe50808ff
  private static let hexed9d13: UInt32 = 0xed9d13ff
  private static let hexff3a3a: UInt32 = 0xff3a3aff
  private static let hexffa500: UInt32 = 0xffa500ff
  private static let hexfff: UInt32 = 0xfffff

  public func getBgColor() -> Color { Color(rgba: Self.hex202020) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hexd0d0d0), bg: Color(rgba: Self.hex202020)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hexababab), bg: Color(rgba: Self.hex202020), italic: true),
      .commentPreproc: TextFormat(fg: Color(rgba: Self.hexff3a3a), bg: Color(rgba: Self.hex202020), bold: true),
      .commentSpecial: TextFormat(fg: Color(rgba: Self.hexe50808), bg: Color(rgba: Self.hex520000), bold: true),
      .error: TextFormat(fg: Color(rgba: Self.hexa61717), bg: Color(rgba: Self.hexe3d2d2)),
      .genericDeleted: TextFormat(fg: Color(rgba: Self.hexff3a3a), bg: Color(rgba: Self.hex202020)),
      .genericEmph: TextFormat(fg: Color(rgba: Self.hexd0d0d0), bg: Color(rgba: Self.hex202020), italic: true),
      .genericEmphStrong: TextFormat(fg: Color(rgba: Self.hexd0d0d0), bg: Color(rgba: Self.hex202020), bold: true, italic: true),
      .genericError: TextFormat(fg: Color(rgba: Self.hexff3a3a), bg: Color(rgba: Self.hex202020)),
      .genericHeading: TextFormat(fg: Color(rgba: Self.hexfff), bg: Color(rgba: Self.hex202020), bold: true),
      .genericInserted: TextFormat(fg: Color(rgba: Self.hex589819), bg: Color(rgba: Self.hex202020)),
      .genericOutput: TextFormat(fg: Color(rgba: Self.hexccc), bg: Color(rgba: Self.hex202020)),
      .genericPrompt: TextFormat(fg: Color(rgba: Self.hexaaa), bg: Color(rgba: Self.hex202020)),
      .genericStrong: TextFormat(fg: Color(rgba: Self.hexd0d0d0), bg: Color(rgba: Self.hex202020), bold: true),
      .genericSubheading: TextFormat(fg: Color(rgba: Self.hexfff), bg: Color(rgba: Self.hex202020), underline: true),
      .genericTraceback: TextFormat(fg: Color(rgba: Self.hexff3a3a), bg: Color(rgba: Self.hex202020)),
      .keyword: TextFormat(fg: Color(rgba: Self.hex6ebf26), bg: Color(rgba: Self.hex202020), bold: true),
      .keywordPseudo: TextFormat(fg: Color(rgba: Self.hex6ebf26), bg: Color(rgba: Self.hex202020)),
      .nameAttribute: TextFormat(fg: Color(rgba: Self.hexbbb), bg: Color(rgba: Self.hex202020)),
      .nameBuiltin: TextFormat(fg: Color(rgba: Self.hex2fbccd), bg: Color(rgba: Self.hex202020)),
      .nameClass: TextFormat(fg: Color(rgba: Self.hex71adff), bg: Color(rgba: Self.hex202020), underline: true),
      .nameConstant: TextFormat(fg: Color(rgba: Self.hex40ffff), bg: Color(rgba: Self.hex202020)),
      .nameDecorator: TextFormat(fg: Color(rgba: Self.hexffa500), bg: Color(rgba: Self.hex202020)),
      .nameException: TextFormat(fg: Color(rgba: Self.hexbbb), bg: Color(rgba: Self.hex202020)),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hex71adff), bg: Color(rgba: Self.hex202020)),
      .nameNamespace: TextFormat(fg: Color(rgba: Self.hex71adff), bg: Color(rgba: Self.hex202020), underline: true),
      .nameTag: TextFormat(fg: Color(rgba: Self.hex6ebf26), bg: Color(rgba: Self.hex202020), bold: true),
      .nameVariable: TextFormat(fg: Color(rgba: Self.hex40ffff), bg: Color(rgba: Self.hex202020)),
      .number: TextFormat(fg: Color(rgba: Self.hex51b2fd), bg: Color(rgba: Self.hex202020)),
      .operatorWord: TextFormat(fg: Color(rgba: Self.hex6ebf26), bg: Color(rgba: Self.hex202020), bold: true),
      .string: TextFormat(fg: Color(rgba: Self.hexed9d13), bg: Color(rgba: Self.hex202020)),
      .stringOther: TextFormat(fg: Color(rgba: Self.hexffa500), bg: Color(rgba: Self.hex202020)),
      .whitespace: TextFormat(fg: Color(rgba: Self.hex666), bg: Color(rgba: Self.hex202020)),
    ]
  }
}
