// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "native" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct NativeTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#202020")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#d0d0d0")!, bg: Color(fromHex: "#202020")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#ababab")!, bg: Color(fromHex: "#202020")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#ff3a3a")!, bg: Color(fromHex: "#202020")!, bold: true),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#e50808")!, bg: Color(fromHex: "#520000")!, bold: true),
      .error: TextFormat(fg: Color(fromHex: "#a61717")!, bg: Color(fromHex: "#e3d2d2")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#ff3a3a")!, bg: Color(fromHex: "#202020")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#d0d0d0")!, bg: Color(fromHex: "#202020")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#d0d0d0")!, bg: Color(fromHex: "#202020")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#ff3a3a")!, bg: Color(fromHex: "#202020")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#202020")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#589819")!, bg: Color(fromHex: "#202020")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#202020")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#aaa")!, bg: Color(fromHex: "#202020")!),
      .genericStrong: TextFormat(fg: Color(fromHex: "#d0d0d0")!, bg: Color(fromHex: "#202020")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#202020")!, underline: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#ff3a3a")!, bg: Color(fromHex: "#202020")!),
      .keyword: TextFormat(fg: Color(fromHex: "#6ebf26")!, bg: Color(fromHex: "#202020")!, bold: true),
      .keywordPseudo: TextFormat(fg: Color(fromHex: "#6ebf26")!, bg: Color(fromHex: "#202020")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#bbb")!, bg: Color(fromHex: "#202020")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#2fbccd")!, bg: Color(fromHex: "#202020")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#71adff")!, bg: Color(fromHex: "#202020")!, underline: true),
      .nameConstant: TextFormat(fg: Color(fromHex: "#40ffff")!, bg: Color(fromHex: "#202020")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#ffa500")!, bg: Color(fromHex: "#202020")!),
      .nameException: TextFormat(fg: Color(fromHex: "#bbb")!, bg: Color(fromHex: "#202020")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#71adff")!, bg: Color(fromHex: "#202020")!),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#71adff")!, bg: Color(fromHex: "#202020")!, underline: true),
      .nameTag: TextFormat(fg: Color(fromHex: "#6ebf26")!, bg: Color(fromHex: "#202020")!, bold: true),
      .nameVariable: TextFormat(fg: Color(fromHex: "#40ffff")!, bg: Color(fromHex: "#202020")!),
      .number: TextFormat(fg: Color(fromHex: "#51b2fd")!, bg: Color(fromHex: "#202020")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#6ebf26")!, bg: Color(fromHex: "#202020")!, bold: true),
      .string: TextFormat(fg: Color(fromHex: "#ed9d13")!, bg: Color(fromHex: "#202020")!),
      .stringOther: TextFormat(fg: Color(fromHex: "#ffa500")!, bg: Color(fromHex: "#202020")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#202020")!),
    ]
  }
}
