// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "nord-darker" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct NordDarkerTheme: CodeTheme {
  public init() {}

  private static let hex242933: UInt32 = 0x242933ff
  private static let hex5e81ac: UInt32 = 0x5e81acff
  private static let hex616e87: UInt32 = 0x616e87ff
  private static let hex616e88: UInt32 = 0x616e88ff
  private static let hex81a1c1: UInt32 = 0x81a1c1ff
  private static let hex88c0d0: UInt32 = 0x88c0d0ff
  private static let hex8fbcbb: UInt32 = 0x8fbcbbff
  private static let hexa3be8c: UInt32 = 0xa3be8cff
  private static let hexb48ead: UInt32 = 0xb48eadff
  private static let hexbf616a: UInt32 = 0xbf616aff
  private static let hexd08770: UInt32 = 0xd08770ff
  private static let hexd8dee9: UInt32 = 0xd8dee9ff
  private static let hexebcb8b: UInt32 = 0xebcb8bff
  private static let hexeceff4: UInt32 = 0xeceff4ff

  public func getBgColor() -> Color { Color(rgba: Self.hex242933) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hexd8dee9), bg: Color(rgba: Self.hex242933)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hex616e87), bg: Color(rgba: Self.hex242933), italic: true),
      .commentPreproc: TextFormat(fg: Color(rgba: Self.hex5e81ac), bg: Color(rgba: Self.hex242933), italic: true),
      .error: TextFormat(fg: Color(rgba: Self.hexbf616a), bg: Color(rgba: Self.hex242933)),
      .genericDeleted: TextFormat(fg: Color(rgba: Self.hexbf616a), bg: Color(rgba: Self.hex242933)),
      .genericEmph: TextFormat(fg: Color(rgba: Self.hexd8dee9), bg: Color(rgba: Self.hex242933), italic: true),
      .genericError: TextFormat(fg: Color(rgba: Self.hexbf616a), bg: Color(rgba: Self.hex242933)),
      .genericHeading: TextFormat(fg: Color(rgba: Self.hex88c0d0), bg: Color(rgba: Self.hex242933), bold: true),
      .genericInserted: TextFormat(fg: Color(rgba: Self.hexa3be8c), bg: Color(rgba: Self.hex242933)),
      .genericPrompt: TextFormat(fg: Color(rgba: Self.hex616e88), bg: Color(rgba: Self.hex242933), bold: true),
      .genericStrong: TextFormat(fg: Color(rgba: Self.hexd8dee9), bg: Color(rgba: Self.hex242933), bold: true),
      .genericSubheading: TextFormat(fg: Color(rgba: Self.hex88c0d0), bg: Color(rgba: Self.hex242933), bold: true),
      .genericTraceback: TextFormat(fg: Color(rgba: Self.hexbf616a), bg: Color(rgba: Self.hex242933)),
      .keyword: TextFormat(fg: Color(rgba: Self.hex81a1c1), bg: Color(rgba: Self.hex242933), bold: true),
      .keywordPseudo: TextFormat(fg: Color(rgba: Self.hex81a1c1), bg: Color(rgba: Self.hex242933)),
      .keywordType: TextFormat(fg: Color(rgba: Self.hex81a1c1), bg: Color(rgba: Self.hex242933)),
      .nameAttribute: TextFormat(fg: Color(rgba: Self.hex8fbcbb), bg: Color(rgba: Self.hex242933)),
      .nameBuiltin: TextFormat(fg: Color(rgba: Self.hex81a1c1), bg: Color(rgba: Self.hex242933)),
      .nameClass: TextFormat(fg: Color(rgba: Self.hex8fbcbb), bg: Color(rgba: Self.hex242933)),
      .nameConstant: TextFormat(fg: Color(rgba: Self.hex8fbcbb), bg: Color(rgba: Self.hex242933)),
      .nameDecorator: TextFormat(fg: Color(rgba: Self.hexd08770), bg: Color(rgba: Self.hex242933)),
      .nameEntity: TextFormat(fg: Color(rgba: Self.hexd08770), bg: Color(rgba: Self.hex242933)),
      .nameException: TextFormat(fg: Color(rgba: Self.hexbf616a), bg: Color(rgba: Self.hex242933)),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hex88c0d0), bg: Color(rgba: Self.hex242933)),
      .nameNamespace: TextFormat(fg: Color(rgba: Self.hex8fbcbb), bg: Color(rgba: Self.hex242933)),
      .nameTag: TextFormat(fg: Color(rgba: Self.hex81a1c1), bg: Color(rgba: Self.hex242933)),
      .number: TextFormat(fg: Color(rgba: Self.hexb48ead), bg: Color(rgba: Self.hex242933)),
      .operator: TextFormat(fg: Color(rgba: Self.hex81a1c1), bg: Color(rgba: Self.hex242933), bold: true),
      .punctuation: TextFormat(fg: Color(rgba: Self.hexeceff4), bg: Color(rgba: Self.hex242933)),
      .string: TextFormat(fg: Color(rgba: Self.hexa3be8c), bg: Color(rgba: Self.hex242933)),
      .stringDoc: TextFormat(fg: Color(rgba: Self.hex616e87), bg: Color(rgba: Self.hex242933)),
      .stringEscape: TextFormat(fg: Color(rgba: Self.hexebcb8b), bg: Color(rgba: Self.hex242933)),
      .stringRegex: TextFormat(fg: Color(rgba: Self.hexebcb8b), bg: Color(rgba: Self.hex242933)),
    ]
  }
}
