// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "nord-darker" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct NordDarkerTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#242933")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#d8dee9")!, bg: Color(fromHex: "#242933")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#616e87")!, bg: Color(fromHex: "#242933")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#5e81ac")!, bg: Color(fromHex: "#242933")!, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#bf616a")!, bg: Color(fromHex: "#242933")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#bf616a")!, bg: Color(fromHex: "#242933")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#d8dee9")!, bg: Color(fromHex: "#242933")!, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#bf616a")!, bg: Color(fromHex: "#242933")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#88c0d0")!, bg: Color(fromHex: "#242933")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#a3be8c")!, bg: Color(fromHex: "#242933")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#616e88")!, bg: Color(fromHex: "#242933")!, bold: true),
      .genericStrong: TextFormat(fg: Color(fromHex: "#d8dee9")!, bg: Color(fromHex: "#242933")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#88c0d0")!, bg: Color(fromHex: "#242933")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#bf616a")!, bg: Color(fromHex: "#242933")!),
      .keyword: TextFormat(fg: Color(fromHex: "#81a1c1")!, bg: Color(fromHex: "#242933")!, bold: true),
      .keywordPseudo: TextFormat(fg: Color(fromHex: "#81a1c1")!, bg: Color(fromHex: "#242933")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#81a1c1")!, bg: Color(fromHex: "#242933")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#8fbcbb")!, bg: Color(fromHex: "#242933")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#81a1c1")!, bg: Color(fromHex: "#242933")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#8fbcbb")!, bg: Color(fromHex: "#242933")!),
      .nameConstant: TextFormat(fg: Color(fromHex: "#8fbcbb")!, bg: Color(fromHex: "#242933")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#d08770")!, bg: Color(fromHex: "#242933")!),
      .nameEntity: TextFormat(fg: Color(fromHex: "#d08770")!, bg: Color(fromHex: "#242933")!),
      .nameException: TextFormat(fg: Color(fromHex: "#bf616a")!, bg: Color(fromHex: "#242933")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#88c0d0")!, bg: Color(fromHex: "#242933")!),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#8fbcbb")!, bg: Color(fromHex: "#242933")!),
      .nameTag: TextFormat(fg: Color(fromHex: "#81a1c1")!, bg: Color(fromHex: "#242933")!),
      .number: TextFormat(fg: Color(fromHex: "#b48ead")!, bg: Color(fromHex: "#242933")!),
      .operator: TextFormat(fg: Color(fromHex: "#81a1c1")!, bg: Color(fromHex: "#242933")!, bold: true),
      .punctuation: TextFormat(fg: Color(fromHex: "#eceff4")!, bg: Color(fromHex: "#242933")!),
      .string: TextFormat(fg: Color(fromHex: "#a3be8c")!, bg: Color(fromHex: "#242933")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#616e87")!, bg: Color(fromHex: "#242933")!),
      .stringEscape: TextFormat(fg: Color(fromHex: "#ebcb8b")!, bg: Color(fromHex: "#242933")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#ebcb8b")!, bg: Color(fromHex: "#242933")!)
    ]
  }
}
