// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "one-dark" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct OneDarkTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#282C34")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#abb2bf")!, bg: Color(fromHex: "#282C34")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#7f848e")!, bg: Color(fromHex: "#282C34")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#e06c75")!, bg: Color(fromHex: "#282C34")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#abb2bf")!, bg: Color(fromHex: "#282C34")!, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#e06c75")!, bg: Color(fromHex: "#282C34")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#abb2bf")!, bg: Color(fromHex: "#282C34")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#98c379")!, bg: Color(fromHex: "#282C34")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#e06c75")!, bg: Color(fromHex: "#282C34")!),
      .genericStrong: TextFormat(fg: Color(fromHex: "#abb2bf")!, bg: Color(fromHex: "#282C34")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#abb2bf")!, bg: Color(fromHex: "#282C34")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#e06c75")!, bg: Color(fromHex: "#282C34")!),
      .keyword: TextFormat(fg: Color(fromHex: "#c678dd")!, bg: Color(fromHex: "#282C34")!),
      .keywordConstant: TextFormat(fg: Color(fromHex: "#e5c07b")!, bg: Color(fromHex: "#282C34")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#e5c07b")!, bg: Color(fromHex: "#282C34")!),
      .name: TextFormat(fg: Color(fromHex: "#e06c75")!, bg: Color(fromHex: "#282C34")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#e5c07b")!, bg: Color(fromHex: "#282C34")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#e5c07b")!, bg: Color(fromHex: "#282C34")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#61afef")!, bg: Color(fromHex: "#282C34")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#61afef")!, bg: Color(fromHex: "#282C34")!, bold: true),
      .nameFunctionMagic: TextFormat(fg: Color(fromHex: "#56b6c2")!, bg: Color(fromHex: "#282C34")!, bold: true),
      .number: TextFormat(fg: Color(fromHex: "#d19a66")!, bg: Color(fromHex: "#282C34")!),
      .operator: TextFormat(fg: Color(fromHex: "#56b6c2")!, bg: Color(fromHex: "#282C34")!),
      .string: TextFormat(fg: Color(fromHex: "#98c379")!, bg: Color(fromHex: "#282C34")!),
    ]
  }
}
