// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "one-dark" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct OneDarkTheme: CodeTheme {
  public init() {}

  private static let hex282c34: UInt32 = 0x282c34ff
  private static let hex56b6c2: UInt32 = 0x56b6c2ff
  private static let hex61afef: UInt32 = 0x61afefff
  private static let hex7f848e: UInt32 = 0x7f848eff
  private static let hex98c379: UInt32 = 0x98c379ff
  private static let hexabb2bf: UInt32 = 0xabb2bfff
  private static let hexc678dd: UInt32 = 0xc678ddff
  private static let hexd19a66: UInt32 = 0xd19a66ff
  private static let hexe06c75: UInt32 = 0xe06c75ff
  private static let hexe5c07b: UInt32 = 0xe5c07bff

  public func getBgColor() -> Color { Color(rgba: Self.hex282c34) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hexabb2bf), bg: Color(rgba: Self.hex282c34)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hex7f848e), bg: Color(rgba: Self.hex282c34)),
      .genericDeleted: TextFormat(fg: Color(rgba: Self.hexe06c75), bg: Color(rgba: Self.hex282c34)),
      .genericEmph: TextFormat(fg: Color(rgba: Self.hexabb2bf), bg: Color(rgba: Self.hex282c34), italic: true),
      .genericError: TextFormat(fg: Color(rgba: Self.hexe06c75), bg: Color(rgba: Self.hex282c34)),
      .genericHeading: TextFormat(fg: Color(rgba: Self.hexabb2bf), bg: Color(rgba: Self.hex282c34), bold: true),
      .genericInserted: TextFormat(fg: Color(rgba: Self.hex98c379), bg: Color(rgba: Self.hex282c34)),
      .genericOutput: TextFormat(fg: Color(rgba: Self.hexe06c75), bg: Color(rgba: Self.hex282c34)),
      .genericStrong: TextFormat(fg: Color(rgba: Self.hexabb2bf), bg: Color(rgba: Self.hex282c34), bold: true),
      .genericSubheading: TextFormat(fg: Color(rgba: Self.hexabb2bf), bg: Color(rgba: Self.hex282c34), bold: true),
      .genericTraceback: TextFormat(fg: Color(rgba: Self.hexe06c75), bg: Color(rgba: Self.hex282c34)),
      .keyword: TextFormat(fg: Color(rgba: Self.hexc678dd), bg: Color(rgba: Self.hex282c34)),
      .keywordConstant: TextFormat(fg: Color(rgba: Self.hexe5c07b), bg: Color(rgba: Self.hex282c34)),
      .keywordType: TextFormat(fg: Color(rgba: Self.hexe5c07b), bg: Color(rgba: Self.hex282c34)),
      .name: TextFormat(fg: Color(rgba: Self.hexe06c75), bg: Color(rgba: Self.hex282c34)),
      .nameBuiltin: TextFormat(fg: Color(rgba: Self.hexe5c07b), bg: Color(rgba: Self.hex282c34)),
      .nameClass: TextFormat(fg: Color(rgba: Self.hexe5c07b), bg: Color(rgba: Self.hex282c34)),
      .nameDecorator: TextFormat(fg: Color(rgba: Self.hex61afef), bg: Color(rgba: Self.hex282c34)),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hex61afef), bg: Color(rgba: Self.hex282c34), bold: true),
      .nameFunctionMagic: TextFormat(fg: Color(rgba: Self.hex56b6c2), bg: Color(rgba: Self.hex282c34), bold: true),
      .number: TextFormat(fg: Color(rgba: Self.hexd19a66), bg: Color(rgba: Self.hex282c34)),
      .operator: TextFormat(fg: Color(rgba: Self.hex56b6c2), bg: Color(rgba: Self.hex282c34)),
      .string: TextFormat(fg: Color(rgba: Self.hex98c379), bg: Color(rgba: Self.hex282c34)),
    ]
  }
}
