// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "paraiso-light" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct ParaisoLightTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#e7e9db")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#e7e9db")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#8d8687")!, bg: Color(fromHex: "#e7e9db")!),
      .error: TextFormat(fg: Color(fromHex: "#ef6155")!, bg: Color(fromHex: "#e7e9db")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#ef6155")!, bg: Color(fromHex: "#e7e9db")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#e7e9db")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#e7e9db")!, bold: true, italic: true),
      .genericHeading: TextFormat(fg: Color(fromHex: "#2f1e2e")!, bg: Color(fromHex: "#e7e9db")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#48b685")!, bg: Color(fromHex: "#e7e9db")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#8d8687")!, bg: Color(fromHex: "#e7e9db")!, bold: true),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#e7e9db")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#5bc4bf")!, bg: Color(fromHex: "#e7e9db")!, bold: true),
      .keyword: TextFormat(fg: Color(fromHex: "#815ba4")!, bg: Color(fromHex: "#e7e9db")!),
      .keywordNamespace: TextFormat(fg: Color(fromHex: "#5bc4bf")!, bg: Color(fromHex: "#e7e9db")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#fec418")!, bg: Color(fromHex: "#e7e9db")!),
      .literal: TextFormat(fg: Color(fromHex: "#f99b15")!, bg: Color(fromHex: "#e7e9db")!),
      .literalDate: TextFormat(fg: Color(fromHex: "#48b685")!, bg: Color(fromHex: "#e7e9db")!),
      .name: TextFormat(fg: Color(fromHex: "#2f1e2e")!, bg: Color(fromHex: "#e7e9db")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#06b6ef")!, bg: Color(fromHex: "#e7e9db")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#fec418")!, bg: Color(fromHex: "#e7e9db")!),
      .nameConstant: TextFormat(fg: Color(fromHex: "#ef6155")!, bg: Color(fromHex: "#e7e9db")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#5bc4bf")!, bg: Color(fromHex: "#e7e9db")!),
      .nameException: TextFormat(fg: Color(fromHex: "#ef6155")!, bg: Color(fromHex: "#e7e9db")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#06b6ef")!, bg: Color(fromHex: "#e7e9db")!),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#fec418")!, bg: Color(fromHex: "#e7e9db")!),
      .nameOther: TextFormat(fg: Color(fromHex: "#06b6ef")!, bg: Color(fromHex: "#e7e9db")!),
      .nameTag: TextFormat(fg: Color(fromHex: "#5bc4bf")!, bg: Color(fromHex: "#e7e9db")!),
      .nameVariable: TextFormat(fg: Color(fromHex: "#ef6155")!, bg: Color(fromHex: "#e7e9db")!),
      .operator: TextFormat(fg: Color(fromHex: "#5bc4bf")!, bg: Color(fromHex: "#e7e9db")!),
      .punctuation: TextFormat(fg: Color(fromHex: "#2f1e2e")!, bg: Color(fromHex: "#e7e9db")!),
      .string: TextFormat(fg: Color(fromHex: "#48b685")!, bg: Color(fromHex: "#e7e9db")!),
      .stringChar: TextFormat(fg: Color(fromHex: "#2f1e2e")!, bg: Color(fromHex: "#e7e9db")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#8d8687")!, bg: Color(fromHex: "#e7e9db")!),
      .stringEscape: TextFormat(fg: Color(fromHex: "#f99b15")!, bg: Color(fromHex: "#e7e9db")!),
      .stringInterpol: TextFormat(fg: Color(fromHex: "#f99b15")!, bg: Color(fromHex: "#e7e9db")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#2f1e2e")!, bg: Color(fromHex: "#e7e9db")!)
    ]
  }
}
