// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "pastie" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct PastieTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#ffffff")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#ffffff")!),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#c00")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#c00")!, bg: Color(fromHex: "#fff0f0")!, bold: true),
      .error: TextFormat(fg: Color(fromHex: "#a61717")!, bg: Color(fromHex: "#e3d2d2")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#fdd")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#a00")!, bg: Color(fromHex: "#ffffff")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#333")!, bg: Color(fromHex: "#ffffff")!),
      .genericInserted: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#dfd")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#ffffff")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#555")!, bg: Color(fromHex: "#ffffff")!),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#ffffff")!),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#a00")!, bg: Color(fromHex: "#ffffff")!),
      .keyword: TextFormat(fg: Color(fromHex: "#080")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .keywordPseudo: TextFormat(fg: Color(fromHex: "#080")!, bg: Color(fromHex: "#ffffff")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#369")!, bg: Color(fromHex: "#ffffff")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#038")!, bg: Color(fromHex: "#ffffff")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#b06")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameConstant: TextFormat(fg: Color(fromHex: "#036")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#555")!, bg: Color(fromHex: "#ffffff")!),
      .nameException: TextFormat(fg: Color(fromHex: "#b06")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameFunction: TextFormat(fg: Color(fromHex: "#06b")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameLabel: TextFormat(fg: Color(fromHex: "#369")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#b06")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameProperty: TextFormat(fg: Color(fromHex: "#369")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameTag: TextFormat(fg: Color(fromHex: "#b06")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameVariable: TextFormat(fg: Color(fromHex: "#369")!, bg: Color(fromHex: "#ffffff")!),
      .nameVariableGlobal: TextFormat(fg: Color(fromHex: "#d70")!, bg: Color(fromHex: "#ffffff")!),
      .nameVariableInstance: TextFormat(fg: Color(fromHex: "#33b")!, bg: Color(fromHex: "#ffffff")!),
      .number: TextFormat(fg: Color(fromHex: "#00d")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .operatorWord: TextFormat(fg: Color(fromHex: "#080")!, bg: Color(fromHex: "#ffffff")!),
      .string: TextFormat(fg: Color(fromHex: "#d20")!, bg: Color(fromHex: "#fff0f0")!),
      .stringEscape: TextFormat(fg: Color(fromHex: "#04d")!, bg: Color(fromHex: "#fff0f0")!),
      .stringInterpol: TextFormat(fg: Color(fromHex: "#33b")!, bg: Color(fromHex: "#fff0f0")!),
      .stringOther: TextFormat(fg: Color(fromHex: "#2b2")!, bg: Color(fromHex: "#f0fff0")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#080")!, bg: Color(fromHex: "#fff0ff")!),
      .stringSymbol: TextFormat(fg: Color(fromHex: "#a60")!, bg: Color(fromHex: "#fff0f0")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#bbb")!, bg: Color(fromHex: "#ffffff")!),
    ]
  }
}
