// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "pastie" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct PastieTheme: CodeTheme {
  public init() {}

  private static let hex000: UInt32 = 0x000ff
  private static let hex000000: UInt32 = 0x000000ff
  private static let hex00d: UInt32 = 0x00dff
  private static let hex036: UInt32 = 0x036ff
  private static let hex038: UInt32 = 0x038ff
  private static let hex04d: UInt32 = 0x04dff
  private static let hex06b: UInt32 = 0x06bff
  private static let hex080: UInt32 = 0x080ff
  private static let hex2b2: UInt32 = 0x2b2ff
  private static let hex333: UInt32 = 0x333ff
  private static let hex33b: UInt32 = 0x33bff
  private static let hex369: UInt32 = 0x369ff
  private static let hex555: UInt32 = 0x555ff
  private static let hex666: UInt32 = 0x666ff
  private static let hex888: UInt32 = 0x888ff
  private static let hexa00: UInt32 = 0xa00ff
  private static let hexa60: UInt32 = 0xa60ff
  private static let hexa61717: UInt32 = 0xa61717ff
  private static let hexb06: UInt32 = 0xb06ff
  private static let hexbbb: UInt32 = 0xbbbff
  private static let hexc00: UInt32 = 0xc00ff
  private static let hexd20: UInt32 = 0xd20ff
  private static let hexd70: UInt32 = 0xd70ff
  private static let hexdfd: UInt32 = 0xdfdff
  private static let hexe3d2d2: UInt32 = 0xe3d2d2ff
  private static let hexf0fff0: UInt32 = 0xf0fff0ff
  private static let hexfdd: UInt32 = 0xfddff
  private static let hexfff0f0: UInt32 = 0xfff0f0ff
  private static let hexfff0ff: UInt32 = 0xfff0ffff
  private static let hexffffff: UInt32 = 0xffffffff

  public func getBgColor() -> Color { Color(rgba: Self.hexffffff) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hex888), bg: Color(rgba: Self.hexffffff)),
      .commentPreproc: TextFormat(fg: Color(rgba: Self.hexc00), bg: Color(rgba: Self.hexffffff), bold: true),
      .commentSpecial: TextFormat(fg: Color(rgba: Self.hexc00), bg: Color(rgba: Self.hexfff0f0), bold: true),
      .error: TextFormat(fg: Color(rgba: Self.hexa61717), bg: Color(rgba: Self.hexe3d2d2)),
      .genericDeleted: TextFormat(fg: Color(rgba: Self.hex000), bg: Color(rgba: Self.hexfdd)),
      .genericEmph: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), italic: true),
      .genericEmphStrong: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true, italic: true),
      .genericError: TextFormat(fg: Color(rgba: Self.hexa00), bg: Color(rgba: Self.hexffffff)),
      .genericHeading: TextFormat(fg: Color(rgba: Self.hex333), bg: Color(rgba: Self.hexffffff)),
      .genericInserted: TextFormat(fg: Color(rgba: Self.hex000), bg: Color(rgba: Self.hexdfd)),
      .genericOutput: TextFormat(fg: Color(rgba: Self.hex888), bg: Color(rgba: Self.hexffffff)),
      .genericPrompt: TextFormat(fg: Color(rgba: Self.hex555), bg: Color(rgba: Self.hexffffff)),
      .genericStrong: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true),
      .genericSubheading: TextFormat(fg: Color(rgba: Self.hex666), bg: Color(rgba: Self.hexffffff)),
      .genericTraceback: TextFormat(fg: Color(rgba: Self.hexa00), bg: Color(rgba: Self.hexffffff)),
      .keyword: TextFormat(fg: Color(rgba: Self.hex080), bg: Color(rgba: Self.hexffffff), bold: true),
      .keywordPseudo: TextFormat(fg: Color(rgba: Self.hex080), bg: Color(rgba: Self.hexffffff)),
      .keywordType: TextFormat(fg: Color(rgba: Self.hex888), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameAttribute: TextFormat(fg: Color(rgba: Self.hex369), bg: Color(rgba: Self.hexffffff)),
      .nameBuiltin: TextFormat(fg: Color(rgba: Self.hex038), bg: Color(rgba: Self.hexffffff)),
      .nameClass: TextFormat(fg: Color(rgba: Self.hexb06), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameConstant: TextFormat(fg: Color(rgba: Self.hex036), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameDecorator: TextFormat(fg: Color(rgba: Self.hex555), bg: Color(rgba: Self.hexffffff)),
      .nameException: TextFormat(fg: Color(rgba: Self.hexb06), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hex06b), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameLabel: TextFormat(fg: Color(rgba: Self.hex369), bg: Color(rgba: Self.hexffffff), italic: true),
      .nameNamespace: TextFormat(fg: Color(rgba: Self.hexb06), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameProperty: TextFormat(fg: Color(rgba: Self.hex369), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameTag: TextFormat(fg: Color(rgba: Self.hexb06), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameVariable: TextFormat(fg: Color(rgba: Self.hex369), bg: Color(rgba: Self.hexffffff)),
      .nameVariableGlobal: TextFormat(fg: Color(rgba: Self.hexd70), bg: Color(rgba: Self.hexffffff)),
      .nameVariableInstance: TextFormat(fg: Color(rgba: Self.hex33b), bg: Color(rgba: Self.hexffffff)),
      .number: TextFormat(fg: Color(rgba: Self.hex00d), bg: Color(rgba: Self.hexffffff), bold: true),
      .operatorWord: TextFormat(fg: Color(rgba: Self.hex080), bg: Color(rgba: Self.hexffffff)),
      .string: TextFormat(fg: Color(rgba: Self.hexd20), bg: Color(rgba: Self.hexfff0f0)),
      .stringEscape: TextFormat(fg: Color(rgba: Self.hex04d), bg: Color(rgba: Self.hexfff0f0)),
      .stringInterpol: TextFormat(fg: Color(rgba: Self.hex33b), bg: Color(rgba: Self.hexfff0f0)),
      .stringOther: TextFormat(fg: Color(rgba: Self.hex2b2), bg: Color(rgba: Self.hexf0fff0)),
      .stringRegex: TextFormat(fg: Color(rgba: Self.hex080), bg: Color(rgba: Self.hexfff0ff)),
      .stringSymbol: TextFormat(fg: Color(rgba: Self.hexa60), bg: Color(rgba: Self.hexfff0f0)),
      .whitespace: TextFormat(fg: Color(rgba: Self.hexbbb), bg: Color(rgba: Self.hexffffff)),
    ]
  }
}
