// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "perldoc" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct PerldocTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#eeeedd")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#eeeedd")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#228b22")!, bg: Color(fromHex: "#eeeedd")!),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#1e889b")!, bg: Color(fromHex: "#eeeedd")!),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#8b008b")!, bg: Color(fromHex: "#eeeedd")!, bold: true),
      .error: TextFormat(fg: Color(fromHex: "#a61717")!, bg: Color(fromHex: "#e3d2d2")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#a00")!, bg: Color(fromHex: "#eeeedd")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#eeeedd")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#eeeedd")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#a00")!, bg: Color(fromHex: "#eeeedd")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#eeeedd")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#0a0")!, bg: Color(fromHex: "#eeeedd")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#eeeedd")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#555")!, bg: Color(fromHex: "#eeeedd")!),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#eeeedd")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#800080")!, bg: Color(fromHex: "#eeeedd")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#a00")!, bg: Color(fromHex: "#eeeedd")!),
      .keyword: TextFormat(fg: Color(fromHex: "#8b008b")!, bg: Color(fromHex: "#eeeedd")!, bold: true),
      .keywordType: TextFormat(fg: Color(fromHex: "#00688b")!, bg: Color(fromHex: "#eeeedd")!, bold: true),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#658b00")!, bg: Color(fromHex: "#eeeedd")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#658b00")!, bg: Color(fromHex: "#eeeedd")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#008b45")!, bg: Color(fromHex: "#eeeedd")!, bold: true),
      .nameConstant: TextFormat(fg: Color(fromHex: "#00688b")!, bg: Color(fromHex: "#eeeedd")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#707a7c")!, bg: Color(fromHex: "#eeeedd")!),
      .nameException: TextFormat(fg: Color(fromHex: "#008b45")!, bg: Color(fromHex: "#eeeedd")!, bold: true),
      .nameFunction: TextFormat(fg: Color(fromHex: "#008b45")!, bg: Color(fromHex: "#eeeedd")!),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#008b45")!, bg: Color(fromHex: "#eeeedd")!, underline: true),
      .nameTag: TextFormat(fg: Color(fromHex: "#8b008b")!, bg: Color(fromHex: "#eeeedd")!, bold: true),
      .nameVariable: TextFormat(fg: Color(fromHex: "#00688b")!, bg: Color(fromHex: "#eeeedd")!),
      .number: TextFormat(fg: Color(fromHex: "#b452cd")!, bg: Color(fromHex: "#eeeedd")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#8b008b")!, bg: Color(fromHex: "#eeeedd")!),
      .string: TextFormat(fg: Color(fromHex: "#cd5555")!, bg: Color(fromHex: "#eeeedd")!),
      .stringHeredoc: TextFormat(fg: Color(fromHex: "#1c7e71")!, bg: Color(fromHex: "#eeeedd")!, italic: true),
      .stringOther: TextFormat(fg: Color(fromHex: "#cb6c20")!, bg: Color(fromHex: "#eeeedd")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#1c7e71")!, bg: Color(fromHex: "#eeeedd")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#bbb")!, bg: Color(fromHex: "#eeeedd")!)
    ]
  }
}
