// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "default" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct PygmentsTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#f8f8f8")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f8f8f8")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#3d7b7b")!, bg: Color(fromHex: "#f8f8f8")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#9c6500")!, bg: Color(fromHex: "#f8f8f8")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#a00000")!, bg: Color(fromHex: "#f8f8f8")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f8f8f8")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f8f8f8")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#e40000")!, bg: Color(fromHex: "#f8f8f8")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#008400")!, bg: Color(fromHex: "#f8f8f8")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#717171")!, bg: Color(fromHex: "#f8f8f8")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#800080")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#04d")!, bg: Color(fromHex: "#f8f8f8")!),
      .keyword: TextFormat(fg: Color(fromHex: "#008000")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .keywordPseudo: TextFormat(fg: Color(fromHex: "#008000")!, bg: Color(fromHex: "#f8f8f8")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#b00040")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#687822")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#008000")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#00f")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .nameConstant: TextFormat(fg: Color(fromHex: "#800")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#a2f")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameEntity: TextFormat(fg: Color(fromHex: "#717171")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .nameException: TextFormat(fg: Color(fromHex: "#cb3f38")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .nameFunction: TextFormat(fg: Color(fromHex: "#00f")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameLabel: TextFormat(fg: Color(fromHex: "#767600")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#00f")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .nameTag: TextFormat(fg: Color(fromHex: "#008000")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .nameVariable: TextFormat(fg: Color(fromHex: "#19177c")!, bg: Color(fromHex: "#f8f8f8")!),
      .number: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#f8f8f8")!),
      .operator: TextFormat(fg: Color(fromHex: "#666")!, bg: Color(fromHex: "#f8f8f8")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#a2f")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .string: TextFormat(fg: Color(fromHex: "#ba2121")!, bg: Color(fromHex: "#f8f8f8")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#ba2121")!, bg: Color(fromHex: "#f8f8f8")!, italic: true),
      .stringEscape: TextFormat(fg: Color(fromHex: "#aa5d1f")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .stringInterpol: TextFormat(fg: Color(fromHex: "#a45a77")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .stringOther: TextFormat(fg: Color(fromHex: "#008000")!, bg: Color(fromHex: "#f8f8f8")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#a45a77")!, bg: Color(fromHex: "#f8f8f8")!),
      .stringSymbol: TextFormat(fg: Color(fromHex: "#19177c")!, bg: Color(fromHex: "#f8f8f8")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#bbb")!, bg: Color(fromHex: "#f8f8f8")!),
    ]
  }
}
