// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "rainbow_dash" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct RainbowDashTheme: CodeTheme {
  public init() {}

  private static let hex000000: UInt32 = 0x000000ff
  private static let hex0080ff: UInt32 = 0x0080ffff
  private static let hex0c6: UInt32 = 0x0c6ff
  private static let hex2c5dcd: UInt32 = 0x2c5dcdff
  private static let hex318495: UInt32 = 0x318495ff
  private static let hex5918bb: UInt32 = 0x5918bbff
  private static let hexaaa: UInt32 = 0xaaaff
  private static let hexc00: UInt32 = 0xc00ff
  private static let hexc5060b: UInt32 = 0xc5060bff
  private static let hexcbcbcb: UInt32 = 0xcbcbcbff
  private static let hexcfc: UInt32 = 0xcfcff
  private static let hexf00: UInt32 = 0xf00ff
  private static let hexfcc: UInt32 = 0xfccff
  private static let hexff8000: UInt32 = 0xff8000ff
  private static let hexfff: UInt32 = 0xfffff
  private static let hexffffff: UInt32 = 0xffffffff

  public func getBgColor() -> Color { Color(rgba: Self.hexffffff) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hex0080ff), bg: Color(rgba: Self.hexffffff), italic: true),
      .commentPreproc: TextFormat(fg: Color(rgba: Self.hex0080ff), bg: Color(rgba: Self.hexffffff)),
      .commentSpecial: TextFormat(fg: Color(rgba: Self.hex0080ff), bg: Color(rgba: Self.hexffffff), bold: true, italic: true),
      .error: TextFormat(fg: Color(rgba: Self.hexfff), bg: Color(rgba: Self.hexc00)),
      .genericDeleted: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexfcc)),
      .genericEmph: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), italic: true),
      .genericEmphStrong: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true, italic: true),
      .genericError: TextFormat(fg: Color(rgba: Self.hexf00), bg: Color(rgba: Self.hexffffff)),
      .genericHeading: TextFormat(fg: Color(rgba: Self.hex2c5dcd), bg: Color(rgba: Self.hexffffff), bold: true),
      .genericInserted: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexcfc)),
      .genericOutput: TextFormat(fg: Color(rgba: Self.hexaaa), bg: Color(rgba: Self.hexffffff)),
      .genericPrompt: TextFormat(fg: Color(rgba: Self.hex2c5dcd), bg: Color(rgba: Self.hexffffff), bold: true),
      .genericStrong: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true),
      .genericSubheading: TextFormat(fg: Color(rgba: Self.hex2c5dcd), bg: Color(rgba: Self.hexffffff), bold: true),
      .genericTraceback: TextFormat(fg: Color(rgba: Self.hexc5060b), bg: Color(rgba: Self.hexffffff)),
      .keyword: TextFormat(fg: Color(rgba: Self.hex2c5dcd), bg: Color(rgba: Self.hexffffff), bold: true),
      .keywordPseudo: TextFormat(fg: Color(rgba: Self.hex2c5dcd), bg: Color(rgba: Self.hexffffff)),
      .keywordType: TextFormat(fg: Color(rgba: Self.hex5918bb), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameAttribute: TextFormat(fg: Color(rgba: Self.hex2c5dcd), bg: Color(rgba: Self.hexffffff), italic: true),
      .nameBuiltin: TextFormat(fg: Color(rgba: Self.hex5918bb), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameClass: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), underline: true),
      .nameConstant: TextFormat(fg: Color(rgba: Self.hex318495), bg: Color(rgba: Self.hexffffff)),
      .nameDecorator: TextFormat(fg: Color(rgba: Self.hexff8000), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameEntity: TextFormat(fg: Color(rgba: Self.hex5918bb), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameException: TextFormat(fg: Color(rgba: Self.hex5918bb), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hexff8000), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameTag: TextFormat(fg: Color(rgba: Self.hex2c5dcd), bg: Color(rgba: Self.hexffffff), bold: true),
      .number: TextFormat(fg: Color(rgba: Self.hex5918bb), bg: Color(rgba: Self.hexffffff), bold: true),
      .operator: TextFormat(fg: Color(rgba: Self.hex2c5dcd), bg: Color(rgba: Self.hexffffff)),
      .operatorWord: TextFormat(fg: Color(rgba: Self.hex2c5dcd), bg: Color(rgba: Self.hexffffff), bold: true),
      .string: TextFormat(fg: Color(rgba: Self.hex0c6), bg: Color(rgba: Self.hexffffff)),
      .stringDoc: TextFormat(fg: Color(rgba: Self.hex0c6), bg: Color(rgba: Self.hexffffff), italic: true),
      .stringEscape: TextFormat(fg: Color(rgba: Self.hexc5060b), bg: Color(rgba: Self.hexffffff), bold: true),
      .stringOther: TextFormat(fg: Color(rgba: Self.hex318495), bg: Color(rgba: Self.hexffffff)),
      .stringSymbol: TextFormat(fg: Color(rgba: Self.hexc5060b), bg: Color(rgba: Self.hexffffff), bold: true),
      .whitespace: TextFormat(fg: Color(rgba: Self.hexcbcbcb), bg: Color(rgba: Self.hexffffff)),
    ]
  }
}
