// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "rainbow_dash" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct RainbowDashTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#ffffff")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#0080ff")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#0080ff")!, bg: Color(fromHex: "#ffffff")!),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#0080ff")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#c00")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#fcc")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#ffffff")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#2c5dcd")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#cfc")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#aaa")!, bg: Color(fromHex: "#ffffff")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#2c5dcd")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#2c5dcd")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#c5060b")!, bg: Color(fromHex: "#ffffff")!),
      .keyword: TextFormat(fg: Color(fromHex: "#2c5dcd")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .keywordPseudo: TextFormat(fg: Color(fromHex: "#2c5dcd")!, bg: Color(fromHex: "#ffffff")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#5918bb")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#2c5dcd")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#5918bb")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameClass: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, underline: true),
      .nameConstant: TextFormat(fg: Color(fromHex: "#318495")!, bg: Color(fromHex: "#ffffff")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#ff8000")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameEntity: TextFormat(fg: Color(fromHex: "#5918bb")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameException: TextFormat(fg: Color(fromHex: "#5918bb")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameFunction: TextFormat(fg: Color(fromHex: "#ff8000")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameTag: TextFormat(fg: Color(fromHex: "#2c5dcd")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .number: TextFormat(fg: Color(fromHex: "#5918bb")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .operator: TextFormat(fg: Color(fromHex: "#2c5dcd")!, bg: Color(fromHex: "#ffffff")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#2c5dcd")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .string: TextFormat(fg: Color(fromHex: "#0c6")!, bg: Color(fromHex: "#ffffff")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#0c6")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .stringEscape: TextFormat(fg: Color(fromHex: "#c5060b")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .stringOther: TextFormat(fg: Color(fromHex: "#318495")!, bg: Color(fromHex: "#ffffff")!),
      .stringSymbol: TextFormat(fg: Color(fromHex: "#c5060b")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .whitespace: TextFormat(fg: Color(fromHex: "#cbcbcb")!, bg: Color(fromHex: "#ffffff")!),
    ]
  }
}
