// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "rrt" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct RrtTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#000000")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#dddddd")!, bg: Color(fromHex: "#000000")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#0f0")!, bg: Color(fromHex: "#000000")!),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#e5e5e5")!, bg: Color(fromHex: "#000000")!),
      .error: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#000000")!),
      .escape: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#000000")!),
      .generic: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#000000")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#000000")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#ff0")!, bg: Color(fromHex: "#000000")!),
      .genericStrong: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#000000")!),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#ff0")!, bg: Color(fromHex: "#000000")!),
      .keyword: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#000000")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#ee82ee")!, bg: Color(fromHex: "#000000")!),
      .literal: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#000000")!),
      .name: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#000000")!),
      .nameConstant: TextFormat(fg: Color(fromHex: "#7fffd4")!, bg: Color(fromHex: "#000000")!),
      .nameEntity: TextFormat(fg: Color(fromHex: "#eedd82")!, bg: Color(fromHex: "#000000")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#ff0")!, bg: Color(fromHex: "#000000")!),
      .nameTag: TextFormat(fg: Color(fromHex: "#7fffd4")!, bg: Color(fromHex: "#000000")!),
      .nameVariable: TextFormat(fg: Color(fromHex: "#eedd82")!, bg: Color(fromHex: "#000000")!),
      .number: TextFormat(fg: Color(fromHex: "#f0f")!, bg: Color(fromHex: "#000000")!),
      .operator: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#000000")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#000000")!),
      .other: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#000000")!),
      .punctuation: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#000000")!),
      .string: TextFormat(fg: Color(fromHex: "#87ceeb")!, bg: Color(fromHex: "#000000")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#ddd")!, bg: Color(fromHex: "#000000")!),
    ]
  }
}
