// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "sas" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct SasTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#ffffff")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#080")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#a61717")!, bg: Color(fromHex: "#e3d2d2")!),
      .generic: TextFormat(fg: Color(fromHex: "#2c2cff")!, bg: Color(fromHex: "#ffffff")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#080")!, bg: Color(fromHex: "#ffffff")!),
      .genericError: TextFormat(fg: Color(fromHex: "#d30202")!, bg: Color(fromHex: "#ffffff")!),
      .keyword: TextFormat(fg: Color(fromHex: "#2c2cff")!, bg: Color(fromHex: "#ffffff")!),
      .keywordConstant: TextFormat(fg: Color(fromHex: "#2c2cff")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .keywordReserved: TextFormat(fg: Color(fromHex: "#353580")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#2c2cff")!, bg: Color(fromHex: "#ffffff")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true),
      .nameVariable: TextFormat(fg: Color(fromHex: "#2c2cff")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .number: TextFormat(fg: Color(fromHex: "#2c8553")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .other: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffe0")!),
      .string: TextFormat(fg: Color(fromHex: "#800080")!, bg: Color(fromHex: "#ffffff")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#bbb")!, bg: Color(fromHex: "#ffffff")!)
    ]
  }
}
