// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "solarized-light" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct SolarizedLightTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#fdf6e3")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#657b83")!, bg: Color(fromHex: "#fdf6e3")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#93a1a1")!, bg: Color(fromHex: "#fdf6e3")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#d33682")!, bg: Color(fromHex: "#fdf6e3")!),
      .commentPreprocFile: TextFormat(fg: Color(fromHex: "#93a1a1")!, bg: Color(fromHex: "#fdf6e3")!),
      .error: TextFormat(fg: Color(fromHex: "#657b83")!, bg: Color(fromHex: "#dc322f")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#dc322f")!, bg: Color(fromHex: "#fdf6e3")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#657b83")!, bg: Color(fromHex: "#fdf6e3")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#657b83")!, bg: Color(fromHex: "#fdf6e3")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#dc322f")!, bg: Color(fromHex: "#fdf6e3")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#657b83")!, bg: Color(fromHex: "#fdf6e3")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#859900")!, bg: Color(fromHex: "#fdf6e3")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#268bd2")!, bg: Color(fromHex: "#fdf6e3")!, bold: true),
      .genericStrong: TextFormat(fg: Color(fromHex: "#657b83")!, bg: Color(fromHex: "#fdf6e3")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#657b83")!, bg: Color(fromHex: "#fdf6e3")!, underline: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#268bd2")!, bg: Color(fromHex: "#fdf6e3")!),
      .keyword: TextFormat(fg: Color(fromHex: "#859900")!, bg: Color(fromHex: "#fdf6e3")!),
      .keywordConstant: TextFormat(fg: Color(fromHex: "#2aa198")!, bg: Color(fromHex: "#fdf6e3")!),
      .keywordDeclaration: TextFormat(fg: Color(fromHex: "#2aa198")!, bg: Color(fromHex: "#fdf6e3")!),
      .keywordNamespace: TextFormat(fg: Color(fromHex: "#cb4b16")!, bg: Color(fromHex: "#fdf6e3")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#b58900")!, bg: Color(fromHex: "#fdf6e3")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#268bd2")!, bg: Color(fromHex: "#fdf6e3")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#268bd2")!, bg: Color(fromHex: "#fdf6e3")!),
      .nameConstant: TextFormat(fg: Color(fromHex: "#268bd2")!, bg: Color(fromHex: "#fdf6e3")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#268bd2")!, bg: Color(fromHex: "#fdf6e3")!),
      .nameEntity: TextFormat(fg: Color(fromHex: "#268bd2")!, bg: Color(fromHex: "#fdf6e3")!),
      .nameException: TextFormat(fg: Color(fromHex: "#268bd2")!, bg: Color(fromHex: "#fdf6e3")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#268bd2")!, bg: Color(fromHex: "#fdf6e3")!),
      .nameLabel: TextFormat(fg: Color(fromHex: "#268bd2")!, bg: Color(fromHex: "#fdf6e3")!),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#268bd2")!, bg: Color(fromHex: "#fdf6e3")!),
      .nameTag: TextFormat(fg: Color(fromHex: "#268bd2")!, bg: Color(fromHex: "#fdf6e3")!),
      .nameVariable: TextFormat(fg: Color(fromHex: "#268bd2")!, bg: Color(fromHex: "#fdf6e3")!),
      .number: TextFormat(fg: Color(fromHex: "#2aa198")!, bg: Color(fromHex: "#fdf6e3")!),
      .operator: TextFormat(fg: Color(fromHex: "#93a1a1")!, bg: Color(fromHex: "#fdf6e3")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#859900")!, bg: Color(fromHex: "#fdf6e3")!),
      .string: TextFormat(fg: Color(fromHex: "#2aa198")!, bg: Color(fromHex: "#fdf6e3")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#93a1a1")!, bg: Color(fromHex: "#fdf6e3")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#cb4b16")!, bg: Color(fromHex: "#fdf6e3")!),
    ]
  }
}
