// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "staroffice" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct StarofficeTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#ffffff")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#ffffff")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#696969")!, bg: Color(fromHex: "#ffffff")!),
      .error: TextFormat(fg: Color(fromHex: "#800000")!, bg: Color(fromHex: "#ffffff")!),
      .literal: TextFormat(fg: Color(fromHex: "#e00")!, bg: Color(fromHex: "#ffffff")!),
      .name: TextFormat(fg: Color(fromHex: "#008000")!, bg: Color(fromHex: "#ffffff")!)
    ]
  }
}
