// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "stata-light" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct StataLightTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#ffffff")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#080")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#a61717")!, bg: Color(fromHex: "#e3d2d2")!),
      .keyword: TextFormat(fg: Color(fromHex: "#353580")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameFunction: TextFormat(fg: Color(fromHex: "#2c2cff")!, bg: Color(fromHex: "#ffffff")!),
      .nameOther: TextFormat(fg: Color(fromHex: "#be646c")!, bg: Color(fromHex: "#ffffff")!),
      .nameVariable: TextFormat(fg: Color(fromHex: "#35baba")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameVariableGlobal: TextFormat(fg: Color(fromHex: "#b5565e")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .number: TextFormat(fg: Color(fromHex: "#2c2cff")!, bg: Color(fromHex: "#ffffff")!),
      .string: TextFormat(fg: Color(fromHex: "#7a2424")!, bg: Color(fromHex: "#ffffff")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#bbb")!, bg: Color(fromHex: "#ffffff")!),
    ]
  }
}
