// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "stata-light" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct StataLightTheme: CodeTheme {
  public init() {}

  private static let hex000000: UInt32 = 0x000000ff
  private static let hex080: UInt32 = 0x080ff
  private static let hex2c2cff: UInt32 = 0x2c2cffff
  private static let hex353580: UInt32 = 0x353580ff
  private static let hex35baba: UInt32 = 0x35babaff
  private static let hex7a2424: UInt32 = 0x7a2424ff
  private static let hexa61717: UInt32 = 0xa61717ff
  private static let hexb5565e: UInt32 = 0xb5565eff
  private static let hexbbb: UInt32 = 0xbbbff
  private static let hexbe646c: UInt32 = 0xbe646cff
  private static let hexe3d2d2: UInt32 = 0xe3d2d2ff
  private static let hexffffff: UInt32 = 0xffffffff

  public func getBgColor() -> Color { Color(rgba: Self.hexffffff) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hex080), bg: Color(rgba: Self.hexffffff), italic: true),
      .error: TextFormat(fg: Color(rgba: Self.hexa61717), bg: Color(rgba: Self.hexe3d2d2)),
      .keyword: TextFormat(fg: Color(rgba: Self.hex353580), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hex2c2cff), bg: Color(rgba: Self.hexffffff)),
      .nameOther: TextFormat(fg: Color(rgba: Self.hexbe646c), bg: Color(rgba: Self.hexffffff)),
      .nameVariable: TextFormat(fg: Color(rgba: Self.hex35baba), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameVariableGlobal: TextFormat(fg: Color(rgba: Self.hexb5565e), bg: Color(rgba: Self.hexffffff), bold: true),
      .number: TextFormat(fg: Color(rgba: Self.hex2c2cff), bg: Color(rgba: Self.hexffffff)),
      .string: TextFormat(fg: Color(rgba: Self.hex7a2424), bg: Color(rgba: Self.hexffffff)),
      .whitespace: TextFormat(fg: Color(rgba: Self.hexbbb), bg: Color(rgba: Self.hexffffff)),
    ]
  }
}
