// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "stata-dark" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct StataDarkTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#232629")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#cccccc")!, bg: Color(fromHex: "#232629")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#777")!, bg: Color(fromHex: "#232629")!, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#a61717")!, bg: Color(fromHex: "#e3d2d2")!),
      .escape: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#232629")!),
      .generic: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#232629")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#232629")!),
      .keyword: TextFormat(fg: Color(fromHex: "#7686bb")!, bg: Color(fromHex: "#232629")!, bold: true),
      .literal: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#232629")!),
      .name: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#232629")!),
      .nameFunction: TextFormat(fg: Color(fromHex: "#6a6aff")!, bg: Color(fromHex: "#232629")!),
      .nameOther: TextFormat(fg: Color(fromHex: "#e2828e")!, bg: Color(fromHex: "#232629")!),
      .nameVariable: TextFormat(fg: Color(fromHex: "#7ab4db")!, bg: Color(fromHex: "#232629")!, bold: true),
      .nameVariableGlobal: TextFormat(fg: Color(fromHex: "#be646c")!, bg: Color(fromHex: "#232629")!, bold: true),
      .number: TextFormat(fg: Color(fromHex: "#4fb8cc")!, bg: Color(fromHex: "#232629")!),
      .operator: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#232629")!),
      .other: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#232629")!),
      .punctuation: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#232629")!),
      .string: TextFormat(fg: Color(fromHex: "#51cc99")!, bg: Color(fromHex: "#232629")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#bbb")!, bg: Color(fromHex: "#232629")!)
    ]
  }
}
