// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "stata-dark" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct StataDarkTheme: CodeTheme {
  public init() {}

  private static let hex232629: UInt32 = 0x232629ff
  private static let hex4fb8cc: UInt32 = 0x4fb8ccff
  private static let hex51cc99: UInt32 = 0x51cc99ff
  private static let hex6a6aff: UInt32 = 0x6a6affff
  private static let hex7686bb: UInt32 = 0x7686bbff
  private static let hex777: UInt32 = 0x777ff
  private static let hex7ab4db: UInt32 = 0x7ab4dbff
  private static let hexa61717: UInt32 = 0xa61717ff
  private static let hexbbb: UInt32 = 0xbbbff
  private static let hexbe646c: UInt32 = 0xbe646cff
  private static let hexccc: UInt32 = 0xcccff
  private static let hexcccccc: UInt32 = 0xccccccff
  private static let hexe2828e: UInt32 = 0xe2828eff
  private static let hexe3d2d2: UInt32 = 0xe3d2d2ff
  private static let hexfff: UInt32 = 0xfffff

  public func getBgColor() -> Color { Color(rgba: Self.hex232629) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hexcccccc), bg: Color(rgba: Self.hex232629)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hex777), bg: Color(rgba: Self.hex232629), italic: true),
      .error: TextFormat(fg: Color(rgba: Self.hexa61717), bg: Color(rgba: Self.hexe3d2d2)),
      .escape: TextFormat(fg: Color(rgba: Self.hexccc), bg: Color(rgba: Self.hex232629)),
      .generic: TextFormat(fg: Color(rgba: Self.hexccc), bg: Color(rgba: Self.hex232629)),
      .genericPrompt: TextFormat(fg: Color(rgba: Self.hexfff), bg: Color(rgba: Self.hex232629)),
      .keyword: TextFormat(fg: Color(rgba: Self.hex7686bb), bg: Color(rgba: Self.hex232629), bold: true),
      .literal: TextFormat(fg: Color(rgba: Self.hexccc), bg: Color(rgba: Self.hex232629)),
      .name: TextFormat(fg: Color(rgba: Self.hexccc), bg: Color(rgba: Self.hex232629)),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hex6a6aff), bg: Color(rgba: Self.hex232629)),
      .nameOther: TextFormat(fg: Color(rgba: Self.hexe2828e), bg: Color(rgba: Self.hex232629)),
      .nameVariable: TextFormat(fg: Color(rgba: Self.hex7ab4db), bg: Color(rgba: Self.hex232629), bold: true),
      .nameVariableGlobal: TextFormat(fg: Color(rgba: Self.hexbe646c), bg: Color(rgba: Self.hex232629), bold: true),
      .number: TextFormat(fg: Color(rgba: Self.hex4fb8cc), bg: Color(rgba: Self.hex232629)),
      .operator: TextFormat(fg: Color(rgba: Self.hexccc), bg: Color(rgba: Self.hex232629)),
      .other: TextFormat(fg: Color(rgba: Self.hexccc), bg: Color(rgba: Self.hex232629)),
      .punctuation: TextFormat(fg: Color(rgba: Self.hexccc), bg: Color(rgba: Self.hex232629)),
      .string: TextFormat(fg: Color(rgba: Self.hex51cc99), bg: Color(rgba: Self.hex232629)),
      .whitespace: TextFormat(fg: Color(rgba: Self.hexbbb), bg: Color(rgba: Self.hex232629)),
    ]
  }
}
