// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "tango" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct TangoTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#f8f8f8")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#f8f8f8")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#8f5902")!, bg: Color(fromHex: "#f8f8f8")!, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#a40000")!, bg: Color(fromHex: "#f8f8f8")!),
      .generic: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#f8f8f8")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#a40000")!, bg: Color(fromHex: "#f8f8f8")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#f8f8f8")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#f8f8f8")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#ef2929")!, bg: Color(fromHex: "#f8f8f8")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#00a000")!, bg: Color(fromHex: "#f8f8f8")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#f8f8f8")!, italic: true),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#8f5902")!, bg: Color(fromHex: "#f8f8f8")!),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#800080")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#a40000")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .keyword: TextFormat(fg: Color(fromHex: "#204a87")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .literal: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#f8f8f8")!),
      .name: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#c4a000")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#204a87")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameBuiltinPseudo: TextFormat(fg: Color(fromHex: "#3465a4")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameDecorator: TextFormat(fg: Color(fromHex: "#5c35cc")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .nameEntity: TextFormat(fg: Color(fromHex: "#ce5c00")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameException: TextFormat(fg: Color(fromHex: "#c00")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .nameLabel: TextFormat(fg: Color(fromHex: "#f57900")!, bg: Color(fromHex: "#f8f8f8")!),
      .nameTag: TextFormat(fg: Color(fromHex: "#204a87")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .number: TextFormat(fg: Color(fromHex: "#0000cf")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .operator: TextFormat(fg: Color(fromHex: "#ce5c00")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .operatorWord: TextFormat(fg: Color(fromHex: "#204a87")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .other: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#f8f8f8")!),
      .punctuation: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#f8f8f8")!, bold: true),
      .string: TextFormat(fg: Color(fromHex: "#4e9a06")!, bg: Color(fromHex: "#f8f8f8")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#8f5902")!, bg: Color(fromHex: "#f8f8f8")!, italic: true),
      .whitespace: TextFormat(fg: Color(fromHex: "#f8f8f8")!, bg: Color(fromHex: "#f8f8f8")!)
    ]
  }
}
