// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "trac" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct TracTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#ffffff")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#998")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#999")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#999")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#a61717")!, bg: Color(fromHex: "#e3d2d2")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#fdd")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#a00")!, bg: Color(fromHex: "#ffffff")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#999")!, bg: Color(fromHex: "#ffffff")!),
      .genericInserted: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#dfd")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#ffffff")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#555")!, bg: Color(fromHex: "#ffffff")!),
      .genericStrong: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#aaa")!, bg: Color(fromHex: "#ffffff")!),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#a00")!, bg: Color(fromHex: "#ffffff")!),
      .keyword: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .keywordType: TextFormat(fg: Color(fromHex: "#458")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#008080")!, bg: Color(fromHex: "#ffffff")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#999")!, bg: Color(fromHex: "#ffffff")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#458")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameConstant: TextFormat(fg: Color(fromHex: "#008080")!, bg: Color(fromHex: "#ffffff")!),
      .nameEntity: TextFormat(fg: Color(fromHex: "#800080")!, bg: Color(fromHex: "#ffffff")!),
      .nameException: TextFormat(fg: Color(fromHex: "#900")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameFunction: TextFormat(fg: Color(fromHex: "#900")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .nameNamespace: TextFormat(fg: Color(fromHex: "#555")!, bg: Color(fromHex: "#ffffff")!),
      .nameTag: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#ffffff")!),
      .nameVariable: TextFormat(fg: Color(fromHex: "#008080")!, bg: Color(fromHex: "#ffffff")!),
      .number: TextFormat(fg: Color(fromHex: "#099")!, bg: Color(fromHex: "#ffffff")!),
      .operator: TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!, bold: true),
      .string: TextFormat(fg: Color(fromHex: "#b84")!, bg: Color(fromHex: "#ffffff")!),
      .stringRegex: TextFormat(fg: Color(fromHex: "#808000")!, bg: Color(fromHex: "#ffffff")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#bbb")!, bg: Color(fromHex: "#ffffff")!)
    ]
  }
}
