// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "trac" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct TracTheme: CodeTheme {
  public init() {}

  private static let hex000: UInt32 = 0x000ff
  private static let hex000000: UInt32 = 0x000000ff
  private static let hex000080: UInt32 = 0x000080ff
  private static let hex008080: UInt32 = 0x008080ff
  private static let hex099: UInt32 = 0x099ff
  private static let hex458: UInt32 = 0x458ff
  private static let hex555: UInt32 = 0x555ff
  private static let hex800080: UInt32 = 0x800080ff
  private static let hex808000: UInt32 = 0x808000ff
  private static let hex888: UInt32 = 0x888ff
  private static let hex900: UInt32 = 0x900ff
  private static let hex998: UInt32 = 0x998ff
  private static let hex999: UInt32 = 0x999ff
  private static let hexa00: UInt32 = 0xa00ff
  private static let hexa61717: UInt32 = 0xa61717ff
  private static let hexaaa: UInt32 = 0xaaaff
  private static let hexb84: UInt32 = 0xb84ff
  private static let hexbbb: UInt32 = 0xbbbff
  private static let hexdfd: UInt32 = 0xdfdff
  private static let hexe3d2d2: UInt32 = 0xe3d2d2ff
  private static let hexfdd: UInt32 = 0xfddff
  private static let hexffffff: UInt32 = 0xffffffff

  public func getBgColor() -> Color { Color(rgba: Self.hexffffff) }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff)) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(rgba: Self.hex998), bg: Color(rgba: Self.hexffffff), italic: true),
      .commentPreproc: TextFormat(fg: Color(rgba: Self.hex999), bg: Color(rgba: Self.hexffffff), bold: true),
      .commentSpecial: TextFormat(fg: Color(rgba: Self.hex999), bg: Color(rgba: Self.hexffffff), bold: true, italic: true),
      .error: TextFormat(fg: Color(rgba: Self.hexa61717), bg: Color(rgba: Self.hexe3d2d2)),
      .genericDeleted: TextFormat(fg: Color(rgba: Self.hex000), bg: Color(rgba: Self.hexfdd)),
      .genericEmph: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), italic: true),
      .genericEmphStrong: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true, italic: true),
      .genericError: TextFormat(fg: Color(rgba: Self.hexa00), bg: Color(rgba: Self.hexffffff)),
      .genericHeading: TextFormat(fg: Color(rgba: Self.hex999), bg: Color(rgba: Self.hexffffff)),
      .genericInserted: TextFormat(fg: Color(rgba: Self.hex000), bg: Color(rgba: Self.hexdfd)),
      .genericOutput: TextFormat(fg: Color(rgba: Self.hex888), bg: Color(rgba: Self.hexffffff)),
      .genericPrompt: TextFormat(fg: Color(rgba: Self.hex555), bg: Color(rgba: Self.hexffffff)),
      .genericStrong: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true),
      .genericSubheading: TextFormat(fg: Color(rgba: Self.hexaaa), bg: Color(rgba: Self.hexffffff)),
      .genericTraceback: TextFormat(fg: Color(rgba: Self.hexa00), bg: Color(rgba: Self.hexffffff)),
      .keyword: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true),
      .keywordType: TextFormat(fg: Color(rgba: Self.hex458), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameAttribute: TextFormat(fg: Color(rgba: Self.hex008080), bg: Color(rgba: Self.hexffffff)),
      .nameBuiltin: TextFormat(fg: Color(rgba: Self.hex999), bg: Color(rgba: Self.hexffffff)),
      .nameClass: TextFormat(fg: Color(rgba: Self.hex458), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameConstant: TextFormat(fg: Color(rgba: Self.hex008080), bg: Color(rgba: Self.hexffffff)),
      .nameEntity: TextFormat(fg: Color(rgba: Self.hex800080), bg: Color(rgba: Self.hexffffff)),
      .nameException: TextFormat(fg: Color(rgba: Self.hex900), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameFunction: TextFormat(fg: Color(rgba: Self.hex900), bg: Color(rgba: Self.hexffffff), bold: true),
      .nameNamespace: TextFormat(fg: Color(rgba: Self.hex555), bg: Color(rgba: Self.hexffffff)),
      .nameTag: TextFormat(fg: Color(rgba: Self.hex000080), bg: Color(rgba: Self.hexffffff)),
      .nameVariable: TextFormat(fg: Color(rgba: Self.hex008080), bg: Color(rgba: Self.hexffffff)),
      .number: TextFormat(fg: Color(rgba: Self.hex099), bg: Color(rgba: Self.hexffffff)),
      .operator: TextFormat(fg: Color(rgba: Self.hex000000), bg: Color(rgba: Self.hexffffff), bold: true),
      .string: TextFormat(fg: Color(rgba: Self.hexb84), bg: Color(rgba: Self.hexffffff)),
      .stringRegex: TextFormat(fg: Color(rgba: Self.hex808000), bg: Color(rgba: Self.hexffffff)),
      .whitespace: TextFormat(fg: Color(rgba: Self.hexbbb), bg: Color(rgba: Self.hexffffff)),
    ]
  }
}
