// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "vim" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct VimTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#000000")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#cccccc")!, bg: Color(fromHex: "#000000")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#000000")!),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#cd0000")!, bg: Color(fromHex: "#000000")!, bold: true),
      .error: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#000000")!),
      .escape: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#000000")!),
      .generic: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#000000")!),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#cd0000")!, bg: Color(fromHex: "#000000")!),
      .genericEmph: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#000000")!, italic: true),
      .genericEmphStrong: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#000000")!, bold: true, italic: true),
      .genericError: TextFormat(fg: Color(fromHex: "#f00")!, bg: Color(fromHex: "#000000")!),
      .genericHeading: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#000000")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#00cd00")!, bg: Color(fromHex: "#000000")!),
      .genericOutput: TextFormat(fg: Color(fromHex: "#888")!, bg: Color(fromHex: "#000000")!),
      .genericPrompt: TextFormat(fg: Color(fromHex: "#000080")!, bg: Color(fromHex: "#000000")!, bold: true),
      .genericStrong: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#000000")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#800080")!, bg: Color(fromHex: "#000000")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#04d")!, bg: Color(fromHex: "#000000")!),
      .keyword: TextFormat(fg: Color(fromHex: "#cdcd00")!, bg: Color(fromHex: "#000000")!),
      .keywordDeclaration: TextFormat(fg: Color(fromHex: "#00cd00")!, bg: Color(fromHex: "#000000")!),
      .keywordNamespace: TextFormat(fg: Color(fromHex: "#cd00cd")!, bg: Color(fromHex: "#000000")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#00cd00")!, bg: Color(fromHex: "#000000")!),
      .literal: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#000000")!),
      .name: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#000000")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#cd00cd")!, bg: Color(fromHex: "#000000")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#00cdcd")!, bg: Color(fromHex: "#000000")!),
      .nameException: TextFormat(fg: Color(fromHex: "#669")!, bg: Color(fromHex: "#000000")!, bold: true),
      .nameVariable: TextFormat(fg: Color(fromHex: "#00cdcd")!, bg: Color(fromHex: "#000000")!),
      .number: TextFormat(fg: Color(fromHex: "#cd00cd")!, bg: Color(fromHex: "#000000")!),
      .operator: TextFormat(fg: Color(fromHex: "#39c")!, bg: Color(fromHex: "#000000")!),
      .operatorWord: TextFormat(fg: Color(fromHex: "#cdcd00")!, bg: Color(fromHex: "#000000")!),
      .other: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#000000")!),
      .punctuation: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#000000")!),
      .string: TextFormat(fg: Color(fromHex: "#cd0000")!, bg: Color(fromHex: "#000000")!),
      .whitespace: TextFormat(fg: Color(fromHex: "#ccc")!, bg: Color(fromHex: "#000000")!),
    ]
  }
}
