// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "xcode" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct XcodeTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#ffffff")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#000000")!, bg: Color(fromHex: "#ffffff")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#177500")!, bg: Color(fromHex: "#ffffff")!),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#633820")!, bg: Color(fromHex: "#ffffff")!),
      .error: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#ffffff")!),
      .keyword: TextFormat(fg: Color(fromHex: "#a90d91")!, bg: Color(fromHex: "#ffffff")!),
      .literal: TextFormat(fg: Color(fromHex: "#1c01ce")!, bg: Color(fromHex: "#ffffff")!),
      .name: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#ffffff")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#836c28")!, bg: Color(fromHex: "#ffffff")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#a90d91")!, bg: Color(fromHex: "#ffffff")!),
      .nameBuiltinPseudo: TextFormat(fg: Color(fromHex: "#5b269a")!, bg: Color(fromHex: "#ffffff")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#3f6e75")!, bg: Color(fromHex: "#ffffff")!),
      .operator: TextFormat(fg: Color(fromHex: "#000")!, bg: Color(fromHex: "#ffffff")!),
      .string: TextFormat(fg: Color(fromHex: "#c41a16")!, bg: Color(fromHex: "#ffffff")!),
      .stringChar: TextFormat(fg: Color(fromHex: "#2300ce")!, bg: Color(fromHex: "#ffffff")!)
    ]
  }
}
