// GENERATED by Tools/GenerateThemes/generate_themes.py from Pygments' own "zenburn" style —
// do not hand-edit. Re-run the script (see its module docstring) to refresh after a Pygments
// version bump instead.
import SwiftUI

public struct ZenburnTheme: CodeTheme {
  public init() {}
  public func getBgColor() -> Color { Color(fromHex: "#3f3f3f")! }

  public var defaultFormat: TextFormat { TextFormat(fg: Color(fromHex: "#dcdccc")!, bg: Color(fromHex: "#3f3f3f")!) }

  public var styles: [CodeAttributes.Value: TextFormat] {
    [
      .comment: TextFormat(fg: Color(fromHex: "#7f9f7f")!, bg: Color(fromHex: "#3f3f3f")!, italic: true),
      .commentPreproc: TextFormat(fg: Color(fromHex: "#dfaf8f")!, bg: Color(fromHex: "#3f3f3f")!, bold: true, italic: true),
      .commentPreprocFile: TextFormat(fg: Color(fromHex: "#cc9393")!, bg: Color(fromHex: "#3f3f3f")!, italic: true),
      .commentSpecial: TextFormat(fg: Color(fromHex: "#dfdfdf")!, bg: Color(fromHex: "#3f3f3f")!, bold: true, italic: true),
      .error: TextFormat(fg: Color(fromHex: "#e37170")!, bg: Color(fromHex: "#3f3f3f")!, bold: true),
      .generic: TextFormat(fg: Color(fromHex: "#ecbcbc")!, bg: Color(fromHex: "#3f3f3f")!, bold: true),
      .genericDeleted: TextFormat(fg: Color(fromHex: "#c3bf9f")!, bg: Color(fromHex: "#313c36")!, bold: true),
      .genericEmph: TextFormat(fg: Color(fromHex: "#fff")!, bg: Color(fromHex: "#3f3f3f")!, bold: true),
      .genericHeading: TextFormat(fg: Color(fromHex: "#efefef")!, bg: Color(fromHex: "#3f3f3f")!, bold: true),
      .genericInserted: TextFormat(fg: Color(fromHex: "#709080")!, bg: Color(fromHex: "#313c36")!, bold: true),
      .genericOutput: TextFormat(fg: Color(fromHex: "#5b605e")!, bg: Color(fromHex: "#3f3f3f")!, bold: true),
      .genericSubheading: TextFormat(fg: Color(fromHex: "#efefef")!, bg: Color(fromHex: "#3f3f3f")!, bold: true),
      .genericTraceback: TextFormat(fg: Color(fromHex: "#80d4aa")!, bg: Color(fromHex: "#2f2f2f")!, bold: true),
      .keyword: TextFormat(fg: Color(fromHex: "#efdcbc")!, bg: Color(fromHex: "#3f3f3f")!),
      .keywordConstant: TextFormat(fg: Color(fromHex: "#dca3a3")!, bg: Color(fromHex: "#3f3f3f")!),
      .keywordDeclaration: TextFormat(fg: Color(fromHex: "#f0dfaf")!, bg: Color(fromHex: "#3f3f3f")!),
      .keywordNamespace: TextFormat(fg: Color(fromHex: "#f0dfaf")!, bg: Color(fromHex: "#3f3f3f")!),
      .keywordType: TextFormat(fg: Color(fromHex: "#dfdfbf")!, bg: Color(fromHex: "#3f3f3f")!, bold: true),
      .literal: TextFormat(fg: Color(fromHex: "#9fafaf")!, bg: Color(fromHex: "#3f3f3f")!),
      .nameAttribute: TextFormat(fg: Color(fromHex: "#efef8f")!, bg: Color(fromHex: "#3f3f3f")!),
      .nameBuiltin: TextFormat(fg: Color(fromHex: "#efef8f")!, bg: Color(fromHex: "#3f3f3f")!),
      .nameClass: TextFormat(fg: Color(fromHex: "#efef8f")!, bg: Color(fromHex: "#3f3f3f")!),
      .nameConstant: TextFormat(fg: Color(fromHex: "#dca3a3")!, bg: Color(fromHex: "#3f3f3f")!),
      .nameEntity: TextFormat(fg: Color(fromHex: "#cfbfaf")!, bg: Color(fromHex: "#3f3f3f")!),
      .nameException: TextFormat(fg: Color(fromHex: "#c3bf9f")!, bg: Color(fromHex: "#3f3f3f")!, bold: true),
      .nameFunction: TextFormat(fg: Color(fromHex: "#efef8f")!, bg: Color(fromHex: "#3f3f3f")!),
      .nameTag: TextFormat(fg: Color(fromHex: "#e89393")!, bg: Color(fromHex: "#3f3f3f")!, bold: true),
      .number: TextFormat(fg: Color(fromHex: "#8cd0d3")!, bg: Color(fromHex: "#3f3f3f")!),
      .numberFloat: TextFormat(fg: Color(fromHex: "#c0bed1")!, bg: Color(fromHex: "#3f3f3f")!),
      .operator: TextFormat(fg: Color(fromHex: "#f0efd0")!, bg: Color(fromHex: "#3f3f3f")!),
      .punctuation: TextFormat(fg: Color(fromHex: "#f0efd0")!, bg: Color(fromHex: "#3f3f3f")!),
      .string: TextFormat(fg: Color(fromHex: "#cc9393")!, bg: Color(fromHex: "#3f3f3f")!),
      .stringDoc: TextFormat(fg: Color(fromHex: "#7f9f7f")!, bg: Color(fromHex: "#3f3f3f")!),
      .stringInterpol: TextFormat(fg: Color(fromHex: "#dca3a3")!, bg: Color(fromHex: "#3f3f3f")!, bold: true)
    ]
  }
}
