[project]
name = "algorithmdetails"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "click>=8.4.2",
    "coloredlogs>=15.0.1",
    "pygments>=2.20.0",
    "zstandard>=0.25.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.1",
]
